package dqmIII.entity.mobEntity;

import cpw.mods.fml.client.registry.RenderingRegistry;
import dqmIII.entity.mobEntity.monsterBoss.DqmEntityDesupisaro1;
import dqmIII.entity.mobEntity.monsterBoss.DqmEntityDesupisaro2;
import dqmIII.entity.mobEntity.monsterBoss.DqmEntityDesupisaro3;
import dqmIII.entity.mobEntity.monsterBoss.DqmEntityEsterk;
import dqmIII.entity.mobEntity.monsterBoss.DqmEntityGod;
import dqmIII.entity.mobEntity.monsterBoss.DqmEntityMasterdoragon;
import dqmIII.entity.mobEntity.monsterBoss.DqmEntityRyuuou;
import dqmIII.entity.mobEntity.monsterBoss.DqmEntityRyuuou2;
import dqmIII.entity.mobEntity.monsterBoss.DqmEntityZoma;
import dqmIII.entity.mobEntity.monsterDay.DqmEntityAyasiikage;
import dqmIII.entity.mobEntity.monsterDay.DqmEntityBigCrow;
import dqmIII.entity.mobEntity.monsterDay.DqmEntityBigguhatto;
import dqmIII.entity.mobEntity.monsterDay.DqmEntityBubsura;
import dqmIII.entity.mobEntity.monsterDay.DqmEntityBurauni;
import dqmIII.entity.mobEntity.monsterDay.DqmEntityButisuraimu;
import dqmIII.entity.mobEntity.monsterDay.DqmEntityDokuroarai;
import dqmIII.entity.mobEntity.monsterDay.DqmEntityDoronuba;
import dqmIII.entity.mobEntity.monsterDay.DqmEntityDorozara;
import dqmIII.entity.mobEntity.monsterDay.DqmEntityDoruido;
import dqmIII.entity.mobEntity.monsterDay.DqmEntityDragosuraimu;
import dqmIII.entity.mobEntity.monsterDay.DqmEntityDucksbill;
import dqmIII.entity.mobEntity.monsterDay.DqmEntityEbiruapple;
import dqmIII.entity.mobEntity.monsterDay.DqmEntityFaratto;
import dqmIII.entity.mobEntity.monsterDay.DqmEntityGaikotu;
import dqmIII.entity.mobEntity.monsterDay.DqmEntityGizumoAZ;
import dqmIII.entity.mobEntity.monsterDay.DqmEntityGuntaigani;
import dqmIII.entity.mobEntity.monsterDay.DqmEntityHitokuikibako;
import dqmIII.entity.mobEntity.monsterDay.DqmEntityHitokuisaberu;
import dqmIII.entity.mobEntity.monsterDay.DqmEntityHoimisura;
import dqmIII.entity.mobEntity.monsterDay.DqmEntityIkkakuusagi;
import dqmIII.entity.mobEntity.monsterDay.DqmEntityItamogu;
import dqmIII.entity.mobEntity.monsterDay.DqmEntityKimera;
import dqmIII.entity.mobEntity.monsterDay.DqmEntityKirapan;
import dqmIII.entity.mobEntity.monsterDay.DqmEntityKirikabuobake;
import dqmIII.entity.mobEntity.monsterDay.DqmEntityMadohando;
import dqmIII.entity.mobEntity.monsterDay.DqmEntityMomon;
import dqmIII.entity.mobEntity.monsterDay.DqmEntityMomonja;
import dqmIII.entity.mobEntity.monsterDay.DqmEntityObakekinoko;
import dqmIII.entity.mobEntity.monsterDay.DqmEntityObakeumiusi;
import dqmIII.entity.mobEntity.monsterDay.DqmEntityOnikozou;
import dqmIII.entity.mobEntity.monsterDay.DqmEntityOokiduti;
import dqmIII.entity.mobEntity.monsterDay.DqmEntityOokutibasi;
import dqmIII.entity.mobEntity.monsterDay.DqmEntityOomedama;
import dqmIII.entity.mobEntity.monsterDay.DqmEntityOonamekuji;
import dqmIII.entity.mobEntity.monsterDay.DqmEntityPapetkozou;
import dqmIII.entity.mobEntity.monsterDay.DqmEntityPurizunyan;
import dqmIII.entity.mobEntity.monsterDay.DqmEntityRemonsuraimu;
import dqmIII.entity.mobEntity.monsterDay.DqmEntityRippusu;
import dqmIII.entity.mobEntity.monsterDay.DqmEntityRiripat;
import dqmIII.entity.mobEntity.monsterDay.DqmEntitySabotenboru;
import dqmIII.entity.mobEntity.monsterDay.DqmEntitySibirekurage;
import dqmIII.entity.mobEntity.monsterDay.DqmEntitySimasimacat;
import dqmIII.entity.mobEntity.monsterDay.DqmEntitySirudokozou;
import dqmIII.entity.mobEntity.monsterDay.DqmEntitySukippaa;
import dqmIII.entity.mobEntity.monsterDay.DqmEntitySunomon;
import dqmIII.entity.mobEntity.monsterDay.DqmEntitySupini;
import dqmIII.entity.mobEntity.monsterDay.DqmEntitySura;
import dqmIII.entity.mobEntity.monsterDay.DqmEntitySuraimubesu;
import dqmIII.entity.mobEntity.monsterDay.DqmEntitySuraimunaito;
import dqmIII.entity.mobEntity.monsterDay.DqmEntitySuraimutawa;
import dqmIII.entity.mobEntity.monsterDay.DqmEntitySuraimutumuri;
import dqmIII.entity.mobEntity.monsterDay.DqmEntityTogebouzu;
import dqmIII.entity.mobEntity.monsterDay.DqmEntityTukaima;
import dqmIII.entity.mobEntity.monsterDay.DqmEntityUzusioking;
import dqmIII.entity.mobEntity.monsterDay.DqmEntityWaraibukuro;
import dqmIII.entity.mobEntity.monsterDay.DqmEntityZinmentyou;
import dqmIII.entity.mobEntity.monsterDay.DqmEntityZukkinya;
import dqmIII.entity.mobEntity.monsterEnd.DqmEntityAkairai;
import dqmIII.entity.mobEntity.monsterEnd.DqmEntityBassaimasin;
import dqmIII.entity.mobEntity.monsterEnd.DqmEntityBatorurex;
import dqmIII.entity.mobEntity.monsterEnd.DqmEntityBiggumoai;
import dqmIII.entity.mobEntity.monsterEnd.DqmEntityBurizado;
import dqmIII.entity.mobEntity.monsterEnd.DqmEntityDakuhobitto;
import dqmIII.entity.mobEntity.monsterEnd.DqmEntityDakunaito;
import dqmIII.entity.mobEntity.monsterEnd.DqmEntityDarktororu;
import dqmIII.entity.mobEntity.monsterEnd.DqmEntityDasudragon;
import dqmIII.entity.mobEntity.monsterEnd.DqmEntityDenga;
import dqmIII.entity.mobEntity.monsterEnd.DqmEntityDesujakkaru;
import dqmIII.entity.mobEntity.monsterEnd.DqmEntityDesunyago;
import dqmIII.entity.mobEntity.monsterEnd.DqmEntityDesusutoka;
import dqmIII.entity.mobEntity.monsterEnd.DqmEntityDragondarknaito;
import dqmIII.entity.mobEntity.monsterEnd.DqmEntityGamegonrejendo;
import dqmIII.entity.mobEntity.monsterEnd.DqmEntityGigantesu;
import dqmIII.entity.mobEntity.monsterEnd.DqmEntityGodraida;
import dqmIII.entity.mobEntity.monsterEnd.DqmEntityGorudensuraimu;
import dqmIII.entity.mobEntity.monsterEnd.DqmEntityJigokunoyoroi;
import dqmIII.entity.mobEntity.monsterEnd.DqmEntityKagenokisi;
import dqmIII.entity.mobEntity.monsterEnd.DqmEntityManemane;
import dqmIII.entity.mobEntity.monsterEnd.DqmEntityPandorabox;
import dqmIII.entity.mobEntity.monsterEnd.DqmEntityRyuiso;
import dqmIII.entity.mobEntity.monsterEnd.DqmEntityTororubonba;
import dqmIII.entity.mobEntity.monsterEtc.DqmEntityFurosutogizumo;
import dqmIII.entity.mobEntity.monsterEtc.DqmEntityGizumo;
import dqmIII.entity.mobEntity.monsterEtc.DqmEntityHiitogizumo;
import dqmIII.entity.mobEntity.monsterEtc.DqmEntityHitokuibako;
import dqmIII.entity.mobEntity.monsterEtc.DqmEntityKingbesu;
import dqmIII.entity.mobEntity.monsterEtc.DqmEntityMimikkukibako;
import dqmIII.entity.mobEntity.monsterEtc.DqmEntityNorowaretaturugi;
import dqmIII.entity.mobEntity.monsterEtc.DqmEntityPandorakibako;
import dqmIII.entity.mobEntity.monsterEtc.DqmEntitySuraimuking;
import dqmIII.entity.mobEntity.monsterEtc.DqmEntityTubo;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityAnkokumajin;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityAroinpu;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityBaburuking;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityBarakku;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityBariidodog;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityBehomasuraimu;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityBiggufeisu;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityBighanma;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityBosutororu;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityBoureikensi;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityBuraddosodo;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityBurakkubejita;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityDarkslime;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityDeddopekka;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityDgizumo;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityDollmaster;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityDoragonsoruja;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityDqmdragon;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityDragonnaito;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityDragonraida;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityEriminator;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityFureimu;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityGamegon;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityGamegonload;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityGanirasu;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityGoldman;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityGoremu;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityGorudentotemu;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityHotatewarabi;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityJigokunohasami;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityKedamon;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityKemunkurusu;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityKimendousi;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityKiraama;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityKirakurabu;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityKiramasin;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityKiramasin2;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityKisudragon;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityKuinsuraimu;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityMagematango;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityMagemomonja;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityMagumaron;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityMajikaruhatto;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityMaounokage;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityMaporena;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityMegazarurokku;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityMetaruhanta;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityMimikku;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityPapettoman;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityPikusi;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityPombom;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityPuyon;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityRedsaikuron;
import dqmIII.entity.mobEntity.monsterHell.DqmEntitySaikuropusu;
import dqmIII.entity.mobEntity.monsterHell.DqmEntitySirubadebiru;
import dqmIII.entity.mobEntity.monsterHell.DqmEntitySiryou;
import dqmIII.entity.mobEntity.monsterHell.DqmEntitySiryounokisi;
import dqmIII.entity.mobEntity.monsterHell.DqmEntitySodofantomu;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityStarkimera;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityStonman;
import dqmIII.entity.mobEntity.monsterHell.DqmEntitySuraimubehomazun;
import dqmIII.entity.mobEntity.monsterHell.DqmEntitySuraimuhaitawa;
import dqmIII.entity.mobEntity.monsterHell.DqmEntitySuraimumadyura;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityTororuking;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityTubokku;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityUmibouzu;
import dqmIII.entity.mobEntity.monsterMetaru.DqmEntityDaiyamondosuraimu;
import dqmIII.entity.mobEntity.monsterMetaru.DqmEntityDragometaru;
import dqmIII.entity.mobEntity.monsterMetaru.DqmEntityGoldenmetalslime;
import dqmIII.entity.mobEntity.monsterMetaru.DqmEntityHagumeta;
import dqmIII.entity.mobEntity.monsterMetaru.DqmEntityHaguremetaruking;
import dqmIII.entity.mobEntity.monsterMetaru.DqmEntityMetaking;
import dqmIII.entity.mobEntity.monsterMetaru.DqmEntityMetaruburazazu;
import dqmIII.entity.mobEntity.monsterMetaru.DqmEntityMetasura;
import dqmIII.entity.mobEntity.monsterMetaru.DqmEntityPuratinaking;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityAkumanosyo;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityAkumanotubo;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityAnimaruzonbi;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityArumiraji;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityAxedoragon;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityBaburin;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityBakudanbebi;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityBakudaniwa;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityBebisatan;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityBehoimisuraimu;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityBehoimusuraimu;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityBerobero;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityBeronyaago;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityBesuking;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityBuchunpa;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityBuraddihando;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityButtizukinya;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityDansunidoru;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityDesufuratta;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityDokuyazukin;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityDoraki;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityDorakima;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityDoroningyou;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityEnzeruslime;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityFgizumo;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityGaikotukensi;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityGappurin;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityGenjutusi;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityGhost;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityGorotuki;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityHerughost;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityHgizumo;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityHitokuiga;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityHoroghost;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityHyouganmajin;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityJeriman;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityKingsura;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityKirapan2;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityKirasuko;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityMapetman;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityMarinsuraimu;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityMatango;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityMeijidoraki;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityMeijikimera;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityMeragosuto;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityMetaruhantaken;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityMetaruraida;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityMetoroghost;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityMinidemon;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityMokomokojuu;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityMrippusu;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityNightwalker;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityObakekyandoru;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityOdoruhouseki;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityPinkmomon;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityRaimusuraimu;
import dqmIII.entity.mobEntity.monsterNight.DqmEntitySamayoutamasii;
import dqmIII.entity.mobEntity.monsterNight.DqmEntitySamayouyoroi;
import dqmIII.entity.mobEntity.monsterNight.DqmEntitySibireageha;
import dqmIII.entity.mobEntity.monsterNight.DqmEntitySibiredanbira;
import dqmIII.entity.mobEntity.monsterNight.DqmEntitySkullgaroo;
import dqmIII.entity.mobEntity.monsterNight.DqmEntitySumairurokku;
import dqmIII.entity.mobEntity.monsterNight.DqmEntitySumoruguru;
import dqmIII.entity.mobEntity.monsterNight.DqmEntitySupekutetto;
import dqmIII.entity.mobEntity.monsterNight.DqmEntitySura2;
import dqmIII.entity.mobEntity.monsterNight.DqmEntitySuraimubogu;
import dqmIII.entity.mobEntity.monsterNight.DqmEntitySuraimuburesu;
import dqmIII.entity.mobEntity.monsterNight.DqmEntitySyado;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityTahodoraki;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityTomosibikozou;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityTonburero;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityTororu;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityTutiwarasi;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityUmiusi;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityYouganmajin;
import dqmIII.entity.mobEntity.monsterSP.DqmEntityAtorasu;
import dqmIII.entity.mobEntity.monsterSP.DqmEntityBazuzu;
import dqmIII.entity.mobEntity.monsterSP.DqmEntityBurasu;
import dqmIII.entity.mobEntity.monsterSP.DqmEntityDarkRamia;
import dqmIII.entity.mobEntity.monsterSP.DqmEntityFureizado;
import dqmIII.entity.mobEntity.monsterSP.DqmEntityGodonheddo;
import dqmIII.entity.mobEntity.monsterSP.DqmEntityKandatakobun;
import dqmIII.entity.mobEntity.monsterSP.DqmEntityKinghidora;
import dqmIII.entity.mobEntity.monsterSP.DqmEntityKiramajinga;
import dqmIII.entity.mobEntity.monsterSP.DqmEntityKiratoti;
import dqmIII.entity.mobEntity.monsterSP.DqmEntityMashougumo;
import dqmIII.entity.mobEntity.monsterSP.DqmEntityMasso;
import dqmIII.entity.mobEntity.monsterSP.DqmEntityPisaronaito;
import dqmIII.entity.mobEntity.monsterSP.DqmEntityPuremiasuraimu;
import dqmIII.entity.mobEntity.monsterSP.DqmEntitySirubamanto;
import dqmIII.entity.mobEntity.monsterSP.DqmEntitySuraimujeneraru;
import dqmIII.entity.mobEntity.monsterSP.DqmEntityTattyan;
import dqmIII.entity.mobEntity.monsterSP.DqmEntityTororubakkosu;
import dqmIII.entity.mobEntity.monsterSP.DqmEntityUragirikozou;
import dqmIII.entity.mobEntity.monsterSP.DqmEntityWanpakusatan;
import dqmIII.entity.mobEntity.monsterSP.DqmEntityYamatanooroti;
import dqmIII.entity.mobEntity.monsterTensei.DqmEntityArukemisuton;
import dqmIII.entity.mobEntity.monsterTensei.DqmEntityBebingosatan;
import dqmIII.entity.mobEntity.monsterTensei.DqmEntityDebirurodo;
import dqmIII.entity.mobEntity.monsterTensei.DqmEntityGoldmanto;
import dqmIII.entity.mobEntity.monsterTensei.DqmEntityGorudenkon;
import dqmIII.entity.mobEntity.monsterTensei.DqmEntityHatonaito;
import dqmIII.entity.mobEntity.monsterTensei.DqmEntityKirapike;
import dqmIII.entity.mobEntity.monsterTensei.DqmEntityKuinmomon;
import dqmIII.entity.mobEntity.monsterTensei.DqmEntityMaaburun;
import dqmIII.entity.mobEntity.monsterTensei.DqmEntityMadrainbow;
import dqmIII.entity.mobEntity.monsterTensei.DqmEntityMetaruhoimin;
import dqmIII.entity.mobEntity.monsterTensei.DqmEntityMomoirosansimai;
import dqmIII.entity.mobEntity.monsterTensei.DqmEntityMoonkimera;
import dqmIII.entity.mobEntity.monsterTensei.DqmEntityNoroinoiwa;
import dqmIII.entity.mobEntity.monsterTensei.DqmEntityPinkbonbon;
import dqmIII.entity.mobEntity.monsterTensei.DqmEntityReddoatya;
import dqmIII.entity.mobEntity.monsterTensei.DqmEntitySabotengold;
import dqmIII.entity.mobEntity.monsterTensei.DqmEntitySeigin;
import dqmIII.entity.mobEntity.monsterTensei.DqmEntityShuvaluts;
import dqmIII.entity.mobEntity.monsterTensei.DqmEntitySirudoaniki;
import dqmIII.entity.mobEntity.monsterTensei.DqmEntitySweetbag;
import dqmIII.entity.mobEntity.monsterTensei.DqmEntityTaipug;
import dqmIII.entity.mobEntity.monsterTensei.DqmEntityTogekonbou;
import dqmIII.entity.mobEntity.monsterTensei.DqmEntityTumurinmama;
import dqmIII.entity.mobEntity.monsterTensei.DqmEntityTyokonuba;
import dqmIII.entity.mobEntity.render.*;
import dqmIII.entity.mobEntity.render2.DqmRenderAxedoragon;
import dqmIII.entity.mobEntity.render2.DqmRenderBassaimasin;
import dqmIII.entity.mobEntity.render2.DqmRenderBebingosatan;
import dqmIII.entity.mobEntity.render2.DqmRenderBesuking;
import dqmIII.entity.mobEntity.render2.DqmRenderBighanma;
import dqmIII.entity.mobEntity.render2.DqmRenderBosutororu;
import dqmIII.entity.mobEntity.render2.DqmRenderBurasu;
import dqmIII.entity.mobEntity.render2.DqmRenderBurizado;
import dqmIII.entity.mobEntity.render2.DqmRenderDansunidoru;
import dqmIII.entity.mobEntity.render2.DqmRenderDarktororu;
import dqmIII.entity.mobEntity.render2.DqmRenderDesunyago;
import dqmIII.entity.mobEntity.render2.DqmRenderDesusutoka;
import dqmIII.entity.mobEntity.render2.DqmRenderDoragonsoruja;
import dqmIII.entity.mobEntity.render2.DqmRenderDoroningyou;
import dqmIII.entity.mobEntity.render2.DqmRenderDoruido;
import dqmIII.entity.mobEntity.render2.DqmRenderEbiruapple;
import dqmIII.entity.mobEntity.render2.DqmRenderEriminator;
import dqmIII.entity.mobEntity.render2.DqmRenderFaratto;
import dqmIII.entity.mobEntity.render2.DqmRenderFureimu;
import dqmIII.entity.mobEntity.render2.DqmRenderFureizado;
import dqmIII.entity.mobEntity.render2.DqmRenderGaikotu;
import dqmIII.entity.mobEntity.render2.DqmRenderGappurin;
import dqmIII.entity.mobEntity.render2.DqmRenderGenjutusi;
import dqmIII.entity.mobEntity.render2.DqmRenderGoldenmetalslime;
import dqmIII.entity.mobEntity.render2.DqmRenderGoldmanto;
import dqmIII.entity.mobEntity.render2.DqmRenderGorotuki;
import dqmIII.entity.mobEntity.render2.DqmRenderHatonaito;
import dqmIII.entity.mobEntity.render2.DqmRenderJigokunoyoroi;
import dqmIII.entity.mobEntity.render2.DqmRenderKandatakobun;
import dqmIII.entity.mobEntity.render2.DqmRenderKedamon;
import dqmIII.entity.mobEntity.render2.DqmRenderKimendousi;
import dqmIII.entity.mobEntity.render2.DqmRenderKinghidora;
import dqmIII.entity.mobEntity.render2.DqmRenderKiraama;
import dqmIII.entity.mobEntity.render2.DqmRenderKiramasin2;
import dqmIII.entity.mobEntity.render2.DqmRenderMadrainbow;
import dqmIII.entity.mobEntity.render2.DqmRenderManemane;
import dqmIII.entity.mobEntity.render2.DqmRenderMasso;
import dqmIII.entity.mobEntity.render2.DqmRenderMetaruhoimin;
import dqmIII.entity.mobEntity.render2.DqmRenderMokomokojuu;
import dqmIII.entity.mobEntity.render2.DqmRenderMomoirosansimai;
import dqmIII.entity.mobEntity.render2.DqmRenderNoroinoiwa;
import dqmIII.entity.mobEntity.render2.DqmRenderPapettoman;
import dqmIII.entity.mobEntity.render2.DqmRenderPinkbonbon;
import dqmIII.entity.mobEntity.render2.DqmRenderPisaronaito;
import dqmIII.entity.mobEntity.render2.DqmRenderPuremiasuraimu;
import dqmIII.entity.mobEntity.render2.DqmRenderRaimusuraimu;
import dqmIII.entity.mobEntity.render2.DqmRenderRemonsuraimu;
import dqmIII.entity.mobEntity.render2.DqmRenderSabotenboru;
import dqmIII.entity.mobEntity.render2.DqmRenderSabotengold;
import dqmIII.entity.mobEntity.render2.DqmRenderSamayouyoroi;
import dqmIII.entity.mobEntity.render2.DqmRenderShuvaluts;
import dqmIII.entity.mobEntity.render2.DqmRenderSirudoaniki;
import dqmIII.entity.mobEntity.render2.DqmRenderSiryou;
import dqmIII.entity.mobEntity.render2.DqmRenderSweetbag;
import dqmIII.entity.mobEntity.render2.DqmRenderTattyan;
import dqmIII.entity.mobEntity.render2.DqmRenderTororu;
import dqmIII.entity.mobEntity.render2.DqmRenderTororubakkosu;
import dqmIII.entity.mobEntity.render2.DqmRenderTororubonba;
import dqmIII.entity.mobEntity.render2.DqmRenderTororuking;
import dqmIII.entity.mobEntity.render2.DqmRenderTumurinmama;
import dqmIII.entity.mobEntity.render2.DqmRenderUragirikozou;

public class MobRenderingRegister {

	public MobRenderingRegister()
	{
		//RenderingRegistry.registerEntityRenderingHandler(EntityMeleeSkeleton.class, new RenderMeleeSkeleton());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntitySura.class, new DqmRenderSura());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityKingsura.class, new DqmRenderKingsura());

		RenderingRegistry.registerEntityRenderingHandler(DqmEntityAyasiikage.class, new DqmRenderAyasiikage());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityBigCrow.class, new DqmRenderBigCrow());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityBigguhatto.class, new DqmRenderBigguhatto());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityBubsura.class, new DqmRenderBubsura());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityBurauni.class, new DqmRenderBurauni());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityButisuraimu.class, new DqmRenderButisuraimu());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityDokuroarai.class, new DqmRenderDokuroarai());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityDoronuba.class, new DqmRenderDoronuba());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityDorozara.class, new DqmRenderDorozara());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityDragosuraimu.class, new DqmRenderDragosuraimu());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityDucksbill.class, new DqmRenderDucksbill());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityGizumo.class, new DqmRenderGizumo());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityGizumoAZ.class, new DqmRenderGizumoAZ());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityGuntaigani.class, new DqmRenderGuntaigani());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityHitokuikibako.class, new DqmRenderHitokuikibako());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityHitokuisaberu.class, new DqmRenderHitokuisaberu());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityHoimisura.class, new DqmRenderHoimisura());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityIkkakuusagi.class, new DqmRenderIkkakuusagi());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityItamogu.class, new DqmRenderItamogu());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityKimera.class, new DqmRenderKimera());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityKirapan.class, new DqmRenderKirapan());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityKirikabuobake.class, new DqmRenderKirikabuobake());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityMadohando.class, new DqmRenderMadohando());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityMomon.class, new DqmRenderMomon());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityMomonja.class, new DqmRenderMomonja());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityObakekinoko.class, new DqmRenderObakekinoko());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityObakeumiusi.class, new DqmRenderObakeumiusi());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityOnikozou.class, new DqmRenderOnikozou());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityOokiduti.class, new DqmRenderOokiduti());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityOokutibasi.class, new DqmRenderOokutibasi());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityOomedama.class, new DqmRenderOomedama());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityOonamekuji.class, new DqmRenderOonamekuji());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityPapetkozou.class, new DqmRenderPapetkozou());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityPurizunyan.class, new DqmRenderPurizunyan());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityRippusu.class, new DqmRenderRippusu());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityRiripat.class, new DqmRenderRiripat());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntitySibirekurage.class, new DqmRenderSibirekurage());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntitySimasimacat.class, new DqmRenderSimasimacat());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntitySirudokozou.class, new DqmRenderSirudokozou());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntitySukippaa.class, new DqmRenderSukippaa());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntitySunomon.class, new DqmRenderSunomon());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntitySupini.class, new DqmRenderSupini());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntitySura.class, new DqmRenderSura());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntitySuraimubesu.class, new DqmRenderSuraimubesu());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntitySuraimunaito.class, new DqmRenderSuraimunaito());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntitySuraimutawa.class, new DqmRenderSuraimutawa());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntitySuraimutumuri.class, new DqmRenderSuraimutumuri());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityTogebouzu.class, new DqmRenderTogebouzu());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityTubo.class, new DqmRenderTubo());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityTukaima.class, new DqmRenderTukaima());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityUzusioking.class, new DqmRenderUzusioking());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityWaraibukuro.class, new DqmRenderWaraibukuro());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityZinmentyou.class, new DqmRenderZinmentyou());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityZukkinya.class, new DqmRenderZukkinya());

		RenderingRegistry.registerEntityRenderingHandler(DqmEntityAkumanosyo.class, new DqmRenderAkumanosyo());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityAkumanotubo.class, new DqmRenderAkumanotubo());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityAnimaruzonbi.class, new DqmRenderAnimaruzonbi());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityArumiraji.class, new DqmRenderArumiraji());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityBaburin.class, new DqmRenderBaburin());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityBakudanbebi.class, new DqmRenderBakudanbebi());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityBakudaniwa.class, new DqmRenderBakudaniwa());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityBebisatan.class, new DqmRenderBebisatan());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityBehoimisuraimu.class, new DqmRenderBehoimisuraimu());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityBehoimusuraimu.class, new DqmRenderBehoimusuraimu());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityBerobero.class, new DqmRenderBerobero());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityBeronyaago.class, new DqmRenderBeronyaago());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityBuchunpa.class, new DqmRenderBuchunpa());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityBuraddihando.class, new DqmRenderBuraddihando());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityButtizukinya.class, new DqmRenderButtizukinya());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityDesufuratta.class, new DqmRenderDesufuratta());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityDokuyazukin.class, new DqmRenderDokuyazukin());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityDoraki.class, new DqmRenderDoraki());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityDorakima.class, new DqmRenderDorakima());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityEnzeruslime.class, new DqmRenderEnzeruslime());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityFgizumo.class, new DqmRenderFgizumo());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityFurosutogizumo.class, new DqmRenderFurosutogizumo());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityGaikotukensi.class, new DqmRenderGaikotukensi());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityGhost.class, new DqmRenderGhost());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityGorudentotemu.class, new DqmRenderGorudentotemu());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityHerughost.class, new DqmRenderHerughost());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityHgizumo.class, new DqmRenderHgizumo());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityHiitogizumo.class, new DqmRenderHiitogizumo());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityHitokuibako.class, new DqmRenderHitokuibako());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityHitokuiga.class, new DqmRenderHitokuiga());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityHoroghost.class, new DqmRenderHoroghost());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityHyouganmajin.class, new DqmRenderHyouganmajin());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityJeriman.class, new DqmRenderJeriman());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityKingsura.class, new DqmRenderKingsura());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityKirapan2.class, new DqmRenderKirapan2());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityKirasuko.class, new DqmRenderKirasuko());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityMapetman.class, new DqmRenderMapetman());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityMarinsuraimu.class, new DqmRenderMarinsuraimu());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityMatango.class, new DqmRenderMatango());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityMeijidoraki.class, new DqmRenderMeijidoraki());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityMeijikimera.class, new DqmRenderMeijikimera());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityMeragosuto.class, new DqmRenderMeragosuto());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityMetaruraida.class, new DqmRenderMetaruraida());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityMetoroghost.class, new DqmRenderMetoroghost());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityMimikku.class, new DqmRenderMimikku());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityMimikkukibako.class, new DqmRenderMimikkukibako());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityMinidemon.class, new DqmRenderMinidemon());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityMrippusu.class, new DqmRenderMrippusu());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityNightwalker.class, new DqmRenderNightwalker());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityObakekyandoru.class, new DqmRenderObakekyandoru());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityOdoruhouseki.class, new DqmRenderOdoruhouseki());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityPinkmomon.class, new DqmRenderPinkmomon());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntitySamayoutamasii.class, new DqmRenderSamayoutamasii());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntitySibireageha.class, new DqmRenderSibireageha());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntitySibiredanbira.class, new DqmRenderSibiredanbira());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntitySkullgaroo.class, new DqmRenderSkullgaroo());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntitySumairurokku.class, new DqmRenderSumairurokku());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntitySumoruguru.class, new DqmRenderSumoruguru());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntitySupekutetto.class, new DqmRenderSupekutetto());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntitySura2.class, new DqmRenderSura2());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntitySuraimubogu.class, new DqmRenderSuraimubogu());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntitySuraimuburesu.class, new DqmRenderSuraimuburesu());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntitySuraimuking.class, new DqmRenderSuraimuking());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntitySyado.class, new DqmRenderSyado());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityTahodoraki.class, new DqmRenderTahodoraki());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityTomosibikozou.class, new DqmRenderTomosibikozou());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityTonburero.class, new DqmRenderTonburero());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityTutiwarasi.class, new DqmRenderTutiwarasi());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityUmiusi.class, new DqmRenderUmiusi());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityYouganmajin.class, new DqmRenderYouganmajin());


		RenderingRegistry.registerEntityRenderingHandler(DqmEntityAnkokumajin.class, new DqmRenderAnkokumajin());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityAroinpu.class, new DqmRenderAroinpu());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityBaburuking.class, new DqmRenderBaburuking());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityBarakku.class, new DqmRenderBarakku());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityBariidodog.class, new DqmRenderBariidodog());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityBatorurex.class, new DqmRenderBatorurex());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityBehomasuraimu.class, new DqmRenderBehomasuraimu());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityBiggufeisu.class, new DqmRenderBiggufeisu());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityBoureikensi.class, new DqmRenderBoureikensi());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityBuraddosodo.class, new DqmRenderBuraddosodo());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityBurakkubejita.class, new DqmRenderBurakkubejita());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityDarkslime.class, new DqmRenderDarkslime());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityDeddopekka.class, new DqmRenderDeddopekka());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityDgizumo.class, new DqmRenderDgizumo());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityDollmaster.class, new DqmRenderDollmaster());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityDqmdragon.class, new DqmRenderDqmdragon());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityDragonnaito.class, new DqmRenderDragonnaito());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityDragonraida.class, new DqmRenderDragonraida());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityGamegon.class, new DqmRenderGamegon());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityGamegonload.class, new DqmRenderGamegonload());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityGanirasu.class, new DqmRenderGanirasu());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityGoldman.class, new DqmRenderGoldman());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityGoremu.class, new DqmRenderGoremu());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityGorudensuraimu.class, new DqmRenderGorudensuraimu());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityHotatewarabi.class, new DqmRenderHotatewarabi());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityJigokunohasami.class, new DqmRenderJigokunohasami());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityKemunkurusu.class, new DqmRenderKemunkurusu());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityKirakurabu.class, new DqmRenderKirakurabu());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityKiramasin.class, new DqmRenderKiramasin());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityKisudragon.class, new DqmRenderKisudragon());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityKuinsuraimu.class, new DqmRenderKuinsuraimu());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityMagematango.class, new DqmRenderMagematango());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityMagemomonja.class, new DqmRenderMagemomonja());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityMagumaron.class, new DqmRenderMagumaron());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityMajikaruhatto.class, new DqmRenderMajikaruhatto());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityMaounokage.class, new DqmRenderMaounokage());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityMaporena.class, new DqmRenderMaporena());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityMegazarurokku.class, new DqmRenderMegazarurokku());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityMetaruhanta.class, new DqmRenderMetaruhanta());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityMetaruhantaken.class, new DqmRenderMetaruhantaken());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityPandorabox.class, new DqmRenderPandorabox());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityPandorakibako.class, new DqmRenderPandorakibako());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityPikusi.class, new DqmRenderPikusi());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityPombom.class, new DqmRenderPombom());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityPuyon.class, new DqmRenderPuyon());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityRedsaikuron.class, new DqmRenderRedsaikuron());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntitySaikuropusu.class, new DqmRenderSaikuropusu());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntitySirubadebiru.class, new DqmRenderSirubadebiru());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntitySiryounokisi.class, new DqmRenderSiryounokisi());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntitySodofantomu.class, new DqmRenderSodofantomu());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityStarkimera.class, new DqmRenderStarkimera());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityStonman.class, new DqmRenderStonman());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntitySuraimubehomazun.class, new DqmRenderSuraimubehomazun());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntitySuraimuhaitawa.class, new DqmRenderSuraimuhaitawa());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntitySuraimumadyura.class, new DqmRenderSuraimumadyura());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityTubokku.class, new DqmRenderTubokku());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityUmibouzu.class, new DqmRenderUmibouzu());


		RenderingRegistry.registerEntityRenderingHandler(DqmEntityAkairai.class, new DqmRenderAkairai());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityBiggumoai.class, new DqmRenderBiggumoai());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityDakuhobitto.class, new DqmRenderDakuhobitto());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityDakunaito.class, new DqmRenderDakunaito());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityDasudragon.class, new DqmRenderDasudragon());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityDebirurodo.class, new DqmRenderDebirurodo());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityDenga.class, new DqmRenderDenga());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityDesujakkaru.class, new DqmRenderDesujakkaru());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityDragondarknaito.class, new DqmRenderDragondarknaito());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityGamegonrejendo.class, new DqmRenderGamegonrejendo());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityGigantesu.class, new DqmRenderGigantesu());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityGodraida.class, new DqmRenderGodraida());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityKagenokisi.class, new DqmRenderKagenokisi());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityRyuiso.class, new DqmRenderRyuiso());


		RenderingRegistry.registerEntityRenderingHandler(DqmEntityArukemisuton.class, new DqmRenderArukemisuton());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityAtorasu.class, new DqmRenderAtorasu());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityGodonheddo.class, new DqmRenderGodonheddo());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityGorudenkon.class, new DqmRenderGorudenkon());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityKirapike.class, new DqmRenderKirapike());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityKiratoti.class, new DqmRenderKiratoti());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityKuinmomon.class, new DqmRenderKuinmomon());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityMaaburun.class, new DqmRenderMaaburun());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityMashougumo.class, new DqmRenderMashougumo());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityMoonkimera.class, new DqmRenderMoonkimera());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityReddoatya.class, new DqmRenderReddoatya());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntitySeigin.class, new DqmRenderSeigin());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntitySirubamanto.class, new DqmRenderSirubamanto());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityTaipug.class, new DqmRenderTaipug());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityTogekonbou.class, new DqmRenderTogekonbou());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityTyokonuba.class, new DqmRenderTyokonuba());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityWanpakusatan.class, new DqmRenderWanpakusatan());

		RenderingRegistry.registerEntityRenderingHandler(DqmEntityDaiyamondosuraimu.class, new DqmRenderDaiyamondosuraimu());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityDragometaru.class, new DqmRenderDragometaru());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityHagumeta.class, new DqmRenderHagumeta());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityHaguremetaruking.class, new DqmRenderHaguremetaruking());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityMetaking.class, new DqmRenderMetaking());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityMetaruburazazu.class, new DqmRenderMetaruburazazu());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityMetasura.class, new DqmRenderMetasura());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityPuratinaking.class, new DqmRenderPuratinaking());

		RenderingRegistry.registerEntityRenderingHandler(DqmEntityBazuzu.class, new DqmRenderBazuzu());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityDarkRamia.class, new DqmRenderDarkRamia());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityDesupisaro1.class, new DqmRenderDesupisaro1());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityDesupisaro2.class, new DqmRenderDesupisaro2());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityDesupisaro3.class, new DqmRenderDesupisaro3());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityEsterk.class, new DqmRenderEsterk());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityGod.class, new DqmRenderGod());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityKiramajinga.class, new DqmRenderKiramajinga());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityMasterdoragon.class, new DqmRenderMasterdoragon());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityNorowaretaturugi.class, new DqmRenderNorowaretaturugi());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityRyuuou.class, new DqmRenderRyuuou());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityRyuuou2.class, new DqmRenderRyuuou2());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntitySuraimujeneraru.class, new DqmRenderSuraimujeneraru());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityYamatanooroti.class, new DqmRenderYamatanooroti());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityZoma.class, new DqmRenderZoma());

		RenderingRegistry.registerEntityRenderingHandler(DqmEntityAxedoragon.class, new DqmRenderAxedoragon());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityBassaimasin.class, new DqmRenderBassaimasin());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityBesuking.class, new DqmRenderBesuking());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityBighanma.class, new DqmRenderBighanma());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityBosutororu.class, new DqmRenderBosutororu());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityBurizado.class, new DqmRenderBurizado());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityDansunidoru.class, new DqmRenderDansunidoru());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityDarktororu.class, new DqmRenderDarktororu());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityDesunyago.class, new DqmRenderDesunyago());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityDoragonsoruja.class, new DqmRenderDoragonsoruja());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityDoroningyou.class, new DqmRenderDoroningyou());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityDoruido.class, new DqmRenderDoruido());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityEbiruapple.class, new DqmRenderEbiruapple());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityFaratto.class, new DqmRenderFaratto());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityFureimu.class, new DqmRenderFureimu());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityGaikotu.class, new DqmRenderGaikotu());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityGappurin.class, new DqmRenderGappurin());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityGenjutusi.class, new DqmRenderGenjutusi());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityGoldmanto.class, new DqmRenderGoldmanto());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityHatonaito.class, new DqmRenderHatonaito());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityJigokunoyoroi.class, new DqmRenderJigokunoyoroi());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityKandatakobun.class, new DqmRenderKandatakobun());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityKedamon.class, new DqmRenderKedamon());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityKimendousi.class, new DqmRenderKimendousi());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityKiraama.class, new DqmRenderKiraama());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityKiramasin2.class, new DqmRenderKiramasin2());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityManemane.class, new DqmRenderManemane());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityMasso.class, new DqmRenderMasso());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityMetaruhoimin.class, new DqmRenderMetaruhoimin());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityMokomokojuu.class, new DqmRenderMokomokojuu());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityMomoirosansimai.class, new DqmRenderMomoirosansimai());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityNoroinoiwa.class, new DqmRenderNoroinoiwa());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityPapettoman.class, new DqmRenderPapettoman());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityPinkbonbon.class, new DqmRenderPinkbonbon());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityPisaronaito.class, new DqmRenderPisaronaito());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityPuremiasuraimu.class, new DqmRenderPuremiasuraimu());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityRaimusuraimu.class, new DqmRenderRaimusuraimu());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityRemonsuraimu.class, new DqmRenderRemonsuraimu());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntitySabotenboru.class, new DqmRenderSabotenboru());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntitySabotengold.class, new DqmRenderSabotengold());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntitySamayouyoroi.class, new DqmRenderSamayouyoroi());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntitySirudoaniki.class, new DqmRenderSirudoaniki());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntitySiryou.class, new DqmRenderSiryou());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityTattyan.class, new DqmRenderTattyan());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityTororu.class, new DqmRenderTororu());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityTororubakkosu.class, new DqmRenderTororubakkosu());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityTororubonba.class, new DqmRenderTororubonba());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityTororuking.class, new DqmRenderTororuking());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityTumurinmama.class, new DqmRenderTumurinmama());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityUragirikozou.class, new DqmRenderUragirikozou());

		RenderingRegistry.registerEntityRenderingHandler(DqmEntityMadrainbow.class, new DqmRenderMadrainbow());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntitySweetbag.class, new DqmRenderSweetbag());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityShuvaluts.class, new DqmRenderShuvaluts());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityBebingosatan.class, new DqmRenderBebingosatan());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityKinghidora.class, new DqmRenderKinghidora());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityKingbesu.class, new DqmRenderKingbesu());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityBurasu.class, new DqmRenderBurasu());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityGoldenmetalslime.class, new DqmRenderGoldenmetalslime());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityFureizado.class, new DqmRenderFureizado());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityGorotuki.class, new DqmRenderGorotuki());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityEriminator.class, new DqmRenderEriminator());
		RenderingRegistry.registerEntityRenderingHandler(DqmEntityDesusutoka.class, new DqmRenderDesusutoka());

	}
}
