package dqmIII.entity.mobEntity;

import cpw.mods.fml.common.registry.EntityRegistry;
import dqmIII.DQM;
import dqmIII.entity.mobEntity.monsterBoss.DqmEntityDesupisaro1;
import dqmIII.entity.mobEntity.monsterBoss.DqmEntityDesupisaro2;
import dqmIII.entity.mobEntity.monsterBoss.DqmEntityDesupisaro3;
import dqmIII.entity.mobEntity.monsterBoss.DqmEntityEsterk;
import dqmIII.entity.mobEntity.monsterBoss.DqmEntityGod;
import dqmIII.entity.mobEntity.monsterBoss.DqmEntityMasterdoragon;
import dqmIII.entity.mobEntity.monsterBoss.DqmEntityRyuuou;
import dqmIII.entity.mobEntity.monsterBoss.DqmEntityRyuuou2;
import dqmIII.entity.mobEntity.monsterBoss.DqmEntityZoma;
import dqmIII.entity.mobEntity.monsterDay.DqmEntityAyasiikage;
import dqmIII.entity.mobEntity.monsterDay.DqmEntityBigCrow;
import dqmIII.entity.mobEntity.monsterDay.DqmEntityBigguhatto;
import dqmIII.entity.mobEntity.monsterDay.DqmEntityBubsura;
import dqmIII.entity.mobEntity.monsterDay.DqmEntityBurauni;
import dqmIII.entity.mobEntity.monsterDay.DqmEntityButisuraimu;
import dqmIII.entity.mobEntity.monsterDay.DqmEntityDokuroarai;
import dqmIII.entity.mobEntity.monsterDay.DqmEntityDoronuba;
import dqmIII.entity.mobEntity.monsterDay.DqmEntityDorozara;
import dqmIII.entity.mobEntity.monsterDay.DqmEntityDoruido;
import dqmIII.entity.mobEntity.monsterDay.DqmEntityDragosuraimu;
import dqmIII.entity.mobEntity.monsterDay.DqmEntityDucksbill;
import dqmIII.entity.mobEntity.monsterDay.DqmEntityEbiruapple;
import dqmIII.entity.mobEntity.monsterDay.DqmEntityFaratto;
import dqmIII.entity.mobEntity.monsterDay.DqmEntityGaikotu;
import dqmIII.entity.mobEntity.monsterDay.DqmEntityGizumoAZ;
import dqmIII.entity.mobEntity.monsterDay.DqmEntityGuntaigani;
import dqmIII.entity.mobEntity.monsterDay.DqmEntityHitokuikibako;
import dqmIII.entity.mobEntity.monsterDay.DqmEntityHitokuisaberu;
import dqmIII.entity.mobEntity.monsterDay.DqmEntityHoimisura;
import dqmIII.entity.mobEntity.monsterDay.DqmEntityIkkakuusagi;
import dqmIII.entity.mobEntity.monsterDay.DqmEntityItamogu;
import dqmIII.entity.mobEntity.monsterDay.DqmEntityKimera;
import dqmIII.entity.mobEntity.monsterDay.DqmEntityKirapan;
import dqmIII.entity.mobEntity.monsterDay.DqmEntityKirikabuobake;
import dqmIII.entity.mobEntity.monsterDay.DqmEntityMadohando;
import dqmIII.entity.mobEntity.monsterDay.DqmEntityMomon;
import dqmIII.entity.mobEntity.monsterDay.DqmEntityMomonja;
import dqmIII.entity.mobEntity.monsterDay.DqmEntityObakekinoko;
import dqmIII.entity.mobEntity.monsterDay.DqmEntityObakeumiusi;
import dqmIII.entity.mobEntity.monsterDay.DqmEntityOnikozou;
import dqmIII.entity.mobEntity.monsterDay.DqmEntityOokiduti;
import dqmIII.entity.mobEntity.monsterDay.DqmEntityOokutibasi;
import dqmIII.entity.mobEntity.monsterDay.DqmEntityOomedama;
import dqmIII.entity.mobEntity.monsterDay.DqmEntityOonamekuji;
import dqmIII.entity.mobEntity.monsterDay.DqmEntityPapetkozou;
import dqmIII.entity.mobEntity.monsterDay.DqmEntityPurizunyan;
import dqmIII.entity.mobEntity.monsterDay.DqmEntityRemonsuraimu;
import dqmIII.entity.mobEntity.monsterDay.DqmEntityRippusu;
import dqmIII.entity.mobEntity.monsterDay.DqmEntityRiripat;
import dqmIII.entity.mobEntity.monsterDay.DqmEntitySabotenboru;
import dqmIII.entity.mobEntity.monsterDay.DqmEntitySibirekurage;
import dqmIII.entity.mobEntity.monsterDay.DqmEntitySimasimacat;
import dqmIII.entity.mobEntity.monsterDay.DqmEntitySirudokozou;
import dqmIII.entity.mobEntity.monsterDay.DqmEntitySukippaa;
import dqmIII.entity.mobEntity.monsterDay.DqmEntitySunomon;
import dqmIII.entity.mobEntity.monsterDay.DqmEntitySupini;
import dqmIII.entity.mobEntity.monsterDay.DqmEntitySura;
import dqmIII.entity.mobEntity.monsterDay.DqmEntitySuraimubesu;
import dqmIII.entity.mobEntity.monsterDay.DqmEntitySuraimunaito;
import dqmIII.entity.mobEntity.monsterDay.DqmEntitySuraimutawa;
import dqmIII.entity.mobEntity.monsterDay.DqmEntitySuraimutumuri;
import dqmIII.entity.mobEntity.monsterDay.DqmEntityTogebouzu;
import dqmIII.entity.mobEntity.monsterDay.DqmEntityTukaima;
import dqmIII.entity.mobEntity.monsterDay.DqmEntityUzusioking;
import dqmIII.entity.mobEntity.monsterDay.DqmEntityWaraibukuro;
import dqmIII.entity.mobEntity.monsterDay.DqmEntityZinmentyou;
import dqmIII.entity.mobEntity.monsterDay.DqmEntityZukkinya;
import dqmIII.entity.mobEntity.monsterEnd.DqmEntityAkairai;
import dqmIII.entity.mobEntity.monsterEnd.DqmEntityBassaimasin;
import dqmIII.entity.mobEntity.monsterEnd.DqmEntityBatorurex;
import dqmIII.entity.mobEntity.monsterEnd.DqmEntityBiggumoai;
import dqmIII.entity.mobEntity.monsterEnd.DqmEntityBurizado;
import dqmIII.entity.mobEntity.monsterEnd.DqmEntityDakuhobitto;
import dqmIII.entity.mobEntity.monsterEnd.DqmEntityDakunaito;
import dqmIII.entity.mobEntity.monsterEnd.DqmEntityDarktororu;
import dqmIII.entity.mobEntity.monsterEnd.DqmEntityDasudragon;
import dqmIII.entity.mobEntity.monsterEnd.DqmEntityDenga;
import dqmIII.entity.mobEntity.monsterEnd.DqmEntityDesujakkaru;
import dqmIII.entity.mobEntity.monsterEnd.DqmEntityDesunyago;
import dqmIII.entity.mobEntity.monsterEnd.DqmEntityDesusutoka;
import dqmIII.entity.mobEntity.monsterEnd.DqmEntityDragondarknaito;
import dqmIII.entity.mobEntity.monsterEnd.DqmEntityGamegonrejendo;
import dqmIII.entity.mobEntity.monsterEnd.DqmEntityGigantesu;
import dqmIII.entity.mobEntity.monsterEnd.DqmEntityGodraida;
import dqmIII.entity.mobEntity.monsterEnd.DqmEntityGorudensuraimu;
import dqmIII.entity.mobEntity.monsterEnd.DqmEntityJigokunoyoroi;
import dqmIII.entity.mobEntity.monsterEnd.DqmEntityKagenokisi;
import dqmIII.entity.mobEntity.monsterEnd.DqmEntityManemane;
import dqmIII.entity.mobEntity.monsterEnd.DqmEntityPandorabox;
import dqmIII.entity.mobEntity.monsterEnd.DqmEntityRyuiso;
import dqmIII.entity.mobEntity.monsterEnd.DqmEntityTororubonba;
import dqmIII.entity.mobEntity.monsterEtc.DqmEntityFurosutogizumo;
import dqmIII.entity.mobEntity.monsterEtc.DqmEntityGizumo;
import dqmIII.entity.mobEntity.monsterEtc.DqmEntityHiitogizumo;
import dqmIII.entity.mobEntity.monsterEtc.DqmEntityHitokuibako;
import dqmIII.entity.mobEntity.monsterEtc.DqmEntityKingbesu;
import dqmIII.entity.mobEntity.monsterEtc.DqmEntityMimikkukibako;
import dqmIII.entity.mobEntity.monsterEtc.DqmEntityNorowaretaturugi;
import dqmIII.entity.mobEntity.monsterEtc.DqmEntityPandorakibako;
import dqmIII.entity.mobEntity.monsterEtc.DqmEntitySuraimuking;
import dqmIII.entity.mobEntity.monsterEtc.DqmEntityTubo;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityAnkokumajin;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityAroinpu;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityBaburuking;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityBarakku;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityBariidodog;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityBehomasuraimu;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityBiggufeisu;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityBighanma;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityBosutororu;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityBoureikensi;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityBuraddosodo;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityBurakkubejita;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityDarkslime;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityDeddopekka;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityDgizumo;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityDollmaster;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityDoragonsoruja;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityDqmdragon;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityDragonnaito;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityDragonraida;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityEriminator;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityFureimu;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityGamegon;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityGamegonload;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityGanirasu;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityGoldman;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityGoremu;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityGorudentotemu;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityHotatewarabi;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityJigokunohasami;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityKedamon;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityKemunkurusu;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityKimendousi;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityKiraama;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityKirakurabu;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityKiramasin;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityKiramasin2;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityKisudragon;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityKuinsuraimu;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityMagematango;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityMagemomonja;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityMagumaron;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityMajikaruhatto;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityMaounokage;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityMaporena;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityMegazarurokku;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityMetaruhanta;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityMimikku;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityPapettoman;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityPikusi;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityPombom;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityPuyon;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityRedsaikuron;
import dqmIII.entity.mobEntity.monsterHell.DqmEntitySaikuropusu;
import dqmIII.entity.mobEntity.monsterHell.DqmEntitySirubadebiru;
import dqmIII.entity.mobEntity.monsterHell.DqmEntitySiryou;
import dqmIII.entity.mobEntity.monsterHell.DqmEntitySiryounokisi;
import dqmIII.entity.mobEntity.monsterHell.DqmEntitySodofantomu;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityStarkimera;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityStonman;
import dqmIII.entity.mobEntity.monsterHell.DqmEntitySuraimubehomazun;
import dqmIII.entity.mobEntity.monsterHell.DqmEntitySuraimuhaitawa;
import dqmIII.entity.mobEntity.monsterHell.DqmEntitySuraimumadyura;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityTororuking;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityTubokku;
import dqmIII.entity.mobEntity.monsterHell.DqmEntityUmibouzu;
import dqmIII.entity.mobEntity.monsterMetaru.DqmEntityDaiyamondosuraimu;
import dqmIII.entity.mobEntity.monsterMetaru.DqmEntityDragometaru;
import dqmIII.entity.mobEntity.monsterMetaru.DqmEntityGoldenmetalslime;
import dqmIII.entity.mobEntity.monsterMetaru.DqmEntityHagumeta;
import dqmIII.entity.mobEntity.monsterMetaru.DqmEntityHaguremetaruking;
import dqmIII.entity.mobEntity.monsterMetaru.DqmEntityMetaking;
import dqmIII.entity.mobEntity.monsterMetaru.DqmEntityMetaruburazazu;
import dqmIII.entity.mobEntity.monsterMetaru.DqmEntityMetasura;
import dqmIII.entity.mobEntity.monsterMetaru.DqmEntityPuratinaking;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityAkumanosyo;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityAkumanotubo;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityAnimaruzonbi;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityArumiraji;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityAxedoragon;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityBaburin;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityBakudanbebi;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityBakudaniwa;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityBebisatan;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityBehoimisuraimu;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityBehoimusuraimu;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityBerobero;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityBeronyaago;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityBesuking;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityBuchunpa;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityBuraddihando;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityButtizukinya;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityDansunidoru;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityDesufuratta;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityDokuyazukin;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityDoraki;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityDorakima;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityDoroningyou;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityEnzeruslime;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityFgizumo;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityGaikotukensi;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityGappurin;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityGenjutusi;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityGhost;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityGorotuki;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityHerughost;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityHgizumo;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityHitokuiga;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityHoroghost;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityHyouganmajin;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityJeriman;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityKingsura;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityKirapan2;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityKirasuko;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityMapetman;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityMarinsuraimu;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityMatango;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityMeijidoraki;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityMeijikimera;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityMeragosuto;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityMetaruhantaken;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityMetaruraida;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityMetoroghost;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityMinidemon;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityMokomokojuu;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityMrippusu;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityNightwalker;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityObakekyandoru;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityOdoruhouseki;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityPinkmomon;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityRaimusuraimu;
import dqmIII.entity.mobEntity.monsterNight.DqmEntitySamayoutamasii;
import dqmIII.entity.mobEntity.monsterNight.DqmEntitySamayouyoroi;
import dqmIII.entity.mobEntity.monsterNight.DqmEntitySibireageha;
import dqmIII.entity.mobEntity.monsterNight.DqmEntitySibiredanbira;
import dqmIII.entity.mobEntity.monsterNight.DqmEntitySkullgaroo;
import dqmIII.entity.mobEntity.monsterNight.DqmEntitySumairurokku;
import dqmIII.entity.mobEntity.monsterNight.DqmEntitySumoruguru;
import dqmIII.entity.mobEntity.monsterNight.DqmEntitySupekutetto;
import dqmIII.entity.mobEntity.monsterNight.DqmEntitySura2;
import dqmIII.entity.mobEntity.monsterNight.DqmEntitySuraimubogu;
import dqmIII.entity.mobEntity.monsterNight.DqmEntitySuraimuburesu;
import dqmIII.entity.mobEntity.monsterNight.DqmEntitySyado;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityTahodoraki;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityTomosibikozou;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityTonburero;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityTororu;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityTutiwarasi;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityUmiusi;
import dqmIII.entity.mobEntity.monsterNight.DqmEntityYouganmajin;
import dqmIII.entity.mobEntity.monsterSP.DqmEntityAtorasu;
import dqmIII.entity.mobEntity.monsterSP.DqmEntityBazuzu;
import dqmIII.entity.mobEntity.monsterSP.DqmEntityBurasu;
import dqmIII.entity.mobEntity.monsterSP.DqmEntityDarkRamia;
import dqmIII.entity.mobEntity.monsterSP.DqmEntityFureizado;
import dqmIII.entity.mobEntity.monsterSP.DqmEntityGodonheddo;
import dqmIII.entity.mobEntity.monsterSP.DqmEntityKandatakobun;
import dqmIII.entity.mobEntity.monsterSP.DqmEntityKinghidora;
import dqmIII.entity.mobEntity.monsterSP.DqmEntityKiramajinga;
import dqmIII.entity.mobEntity.monsterSP.DqmEntityKiratoti;
import dqmIII.entity.mobEntity.monsterSP.DqmEntityMashougumo;
import dqmIII.entity.mobEntity.monsterSP.DqmEntityMasso;
import dqmIII.entity.mobEntity.monsterSP.DqmEntityPisaronaito;
import dqmIII.entity.mobEntity.monsterSP.DqmEntityPuremiasuraimu;
import dqmIII.entity.mobEntity.monsterSP.DqmEntitySirubamanto;
import dqmIII.entity.mobEntity.monsterSP.DqmEntitySuraimujeneraru;
import dqmIII.entity.mobEntity.monsterSP.DqmEntityTattyan;
import dqmIII.entity.mobEntity.monsterSP.DqmEntityTororubakkosu;
import dqmIII.entity.mobEntity.monsterSP.DqmEntityUragirikozou;
import dqmIII.entity.mobEntity.monsterSP.DqmEntityWanpakusatan;
import dqmIII.entity.mobEntity.monsterSP.DqmEntityYamatanooroti;
import dqmIII.entity.mobEntity.monsterTensei.DqmEntityArukemisuton;
import dqmIII.entity.mobEntity.monsterTensei.DqmEntityBebingosatan;
import dqmIII.entity.mobEntity.monsterTensei.DqmEntityDebirurodo;
import dqmIII.entity.mobEntity.monsterTensei.DqmEntityGoldmanto;
import dqmIII.entity.mobEntity.monsterTensei.DqmEntityGorudenkon;
import dqmIII.entity.mobEntity.monsterTensei.DqmEntityHatonaito;
import dqmIII.entity.mobEntity.monsterTensei.DqmEntityKirapike;
import dqmIII.entity.mobEntity.monsterTensei.DqmEntityKuinmomon;
import dqmIII.entity.mobEntity.monsterTensei.DqmEntityMaaburun;
import dqmIII.entity.mobEntity.monsterTensei.DqmEntityMadrainbow;
import dqmIII.entity.mobEntity.monsterTensei.DqmEntityMetaruhoimin;
import dqmIII.entity.mobEntity.monsterTensei.DqmEntityMomoirosansimai;
import dqmIII.entity.mobEntity.monsterTensei.DqmEntityMoonkimera;
import dqmIII.entity.mobEntity.monsterTensei.DqmEntityNoroinoiwa;
import dqmIII.entity.mobEntity.monsterTensei.DqmEntityPinkbonbon;
import dqmIII.entity.mobEntity.monsterTensei.DqmEntityReddoatya;
import dqmIII.entity.mobEntity.monsterTensei.DqmEntitySabotengold;
import dqmIII.entity.mobEntity.monsterTensei.DqmEntitySeigin;
import dqmIII.entity.mobEntity.monsterTensei.DqmEntityShuvaluts;
import dqmIII.entity.mobEntity.monsterTensei.DqmEntitySirudoaniki;
import dqmIII.entity.mobEntity.monsterTensei.DqmEntitySweetbag;
import dqmIII.entity.mobEntity.monsterTensei.DqmEntityTaipug;
import dqmIII.entity.mobEntity.monsterTensei.DqmEntityTogekonbou;
import dqmIII.entity.mobEntity.monsterTensei.DqmEntityTumurinmama;
import dqmIII.entity.mobEntity.monsterTensei.DqmEntityTyokonuba;

public class MobRegister {

	private int idxID = DQM.conf.MonsterIDidx;

	public MobRegister()
	{
		//EntityRegistry.registerModEntity(EntityMeleeSkeleton.class, "MeleeSkeleton", 0, DQM.instance, 250, 1, false);
		//EntityRegistry.registerModEntity(DqmEntitySura.class, "Suraimu", idxID + 8000, DQM.instance, 250, 1, false);
		//EntityRegistry.registerModEntity(DqmEntityKingsura.class, "Kingsura", idxID + 8001, DQM.instance, 250, 1, false);
		//EntityRegistry.registerModEntity(EntitySample.class, "SampleEntity", 99, DQM.instance, 250, 1, false);

		EntityRegistry.registerModEntity(DqmEntityAyasiikage.class, "Ayasiikage", idxID + 4, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityBigCrow.class, "BigCrow", idxID + 5, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityBigguhatto.class, "Bigguhatto", idxID + 6, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityBubsura.class, "Bubsura", idxID + 7, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityBurauni.class, "Burauni", idxID + 8, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityButisuraimu.class, "Butisuraimu", idxID + 9, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityDokuroarai.class, "Dokuroarai", idxID + 10, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityDoronuba.class, "Doronuba", idxID + 11, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityDorozara.class, "Dorozara", idxID + 12, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityDragosuraimu.class, "Dragosuraimu", idxID + 13, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityDucksbill.class, "Ducksbill", idxID + 14, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityGizumo.class, "Gizumo", idxID + 15, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityGizumoAZ.class, "GizumoAZ", idxID + 16, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityGuntaigani.class, "Guntaigani", idxID + 17, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityHitokuikibako.class, "Hitokuikibako", idxID + 18, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityHitokuisaberu.class, "Hitokuisaberu", idxID + 19, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityHoimisura.class, "Hoimisura", idxID + 20, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityIkkakuusagi.class, "Ikkakuusagi", idxID + 21, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityItamogu.class, "Itamogu", idxID + 22, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityKimera.class, "Kimera", idxID + 23, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityKirapan.class, "Kirapan", idxID + 24, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityKirikabuobake.class, "Kirikabuobake", idxID + 25, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityMadohando.class, "Madohando", idxID + 26, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityMomon.class, "Momon", idxID + 27, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityMomonja.class, "Momonja", idxID + 28, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityObakekinoko.class, "Obakekinoko", idxID + 29, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityObakeumiusi.class, "Obakeumiusi", idxID + 30, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityOnikozou.class, "Onikozou", idxID + 31, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityOokiduti.class, "Ookiduti", idxID + 32, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityOokutibasi.class, "Ookutibasi", idxID + 33, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityOomedama.class, "Oomedama", idxID + 34, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityOonamekuji.class, "Oonamekuji", idxID + 35, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityPapetkozou.class, "Papetkozou", idxID + 36, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityPurizunyan.class, "Purizunyan", idxID + 37, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityRippusu.class, "Rippusu", idxID + 38, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityRiripat.class, "Riripat", idxID + 39, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntitySibirekurage.class, "Sibirekurage", idxID + 40, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntitySimasimacat.class, "Simasimacat", idxID + 41, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntitySirudokozou.class, "Sirudokozou", idxID + 42, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntitySukippaa.class, "Sukippaa", idxID + 43, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntitySunomon.class, "Sunomon", idxID + 44, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntitySupini.class, "Supini", idxID + 45, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntitySura.class, "Sura", idxID + 46, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntitySuraimubesu.class, "Suraimubesu", idxID + 47, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntitySuraimunaito.class, "Suraimunaito", idxID + 48, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntitySuraimutawa.class, "Suraimutawa", idxID + 49, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntitySuraimutumuri.class, "Suraimutumuri", idxID + 50, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityTogebouzu.class, "Togebouzu", idxID + 51, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityTubo.class, "Tubo", idxID + 52, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityTukaima.class, "Tukaima", idxID + 53, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityUzusioking.class, "Uzusioking", idxID + 54, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityWaraibukuro.class, "Waraibukuro", idxID + 55, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityZinmentyou.class, "Zinmentyou", idxID + 56, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityZukkinya.class, "Zukkinya", idxID + 57, DQM.instance, 250, 1, false);


		EntityRegistry.registerModEntity(DqmEntityAkumanosyo.class, "Akumanosyo", idxID + 60, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityAkumanotubo.class, "Akumanotubo", idxID + 61, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityAnimaruzonbi.class, "Animaruzonbi", idxID + 64, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityArumiraji.class, "Arumiraji", idxID + 65, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityBaburin.class, "Baburin", idxID + 66, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityBakudanbebi.class, "Bakudanbebi", idxID + 67, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityBakudaniwa.class, "Bakudaniwa", idxID + 68, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityBebisatan.class, "Bebisatan", idxID + 69, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityBehoimisuraimu.class, "Behoimisuraimu", idxID + 70, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityBehoimusuraimu.class, "Behoimusuraimu", idxID + 71, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityBerobero.class, "Berobero", idxID + 72, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityBeronyaago.class, "Beronyaago", idxID + 73, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityBuchunpa.class, "Buchunpa", idxID + 74, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityBuraddihando.class, "Buraddihando", idxID + 75, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityButtizukinya.class, "Buttizukinya", idxID + 76, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityDesufuratta.class, "Desufuratta", idxID + 77, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityDokuyazukin.class, "Dokuyazukin", idxID + 78, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityDoraki.class, "Doraki", idxID + 79, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityDorakima.class, "Dorakima", idxID + 80, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityEnzeruslime.class, "Enzeruslime", idxID + 81, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityFgizumo.class, "Fgizumo", idxID + 82, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityFurosutogizumo.class, "Furosutogizumo", idxID + 83, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityGaikotukensi.class, "Gaikotukensi", idxID + 84, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityGhost.class, "Ghost", idxID + 85, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityGorudentotemu.class, "Gorudentotemu", idxID + 86, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityHerughost.class, "Herughost", idxID + 87, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityHgizumo.class, "Hgizumo", idxID + 88, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityHiitogizumo.class, "Hiitogizumo", idxID + 89, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityHitokuibako.class, "Hitokuibako", idxID + 90, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityHitokuiga.class, "Hitokuiga", idxID + 91, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityHoroghost.class, "Horoghost", idxID + 92, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityHyouganmajin.class, "Hyouganmajin", idxID + 93, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityJeriman.class, "Jeriman", idxID + 94, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityKingsura.class, "Kingsura", idxID + 95, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityKirapan2.class, "Kirapan2", idxID + 96, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityKirasuko.class, "Kirasuko", idxID + 97, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityMapetman.class, "Mapetman", idxID + 98, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityMarinsuraimu.class, "Marinsuraimu", idxID + 99, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityMatango.class, "Matango", idxID + 100, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityMeijidoraki.class, "Meijidoraki", idxID + 101, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityMeijikimera.class, "Meijikimera", idxID + 102, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityMeragosuto.class, "Meragosuto", idxID + 103, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityMetaruraida.class, "Metaruraida", idxID + 104, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityMetoroghost.class, "Metoroghost", idxID + 105, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityMimikku.class, "Mimikku", idxID + 106, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityMimikkukibako.class, "Mimikkukibako", idxID + 107, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityMinidemon.class, "Minidemon", idxID + 108, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityMrippusu.class, "Mrippusu", idxID + 109, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityNightwalker.class, "Nightwalker", idxID + 110, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityObakekyandoru.class, "Obakekyandoru", idxID + 111, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityOdoruhouseki.class, "Odoruhouseki", idxID + 112, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityPinkmomon.class, "Pinkmomon", idxID + 113, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntitySamayoutamasii.class, "Samayoutamasii", idxID + 114, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntitySibireageha.class, "Sibireageha", idxID + 115, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntitySibiredanbira.class, "Sibiredanbira", idxID + 116, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntitySkullgaroo.class, "Skullgaroo", idxID + 117, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntitySumairurokku.class, "Sumairurokku", idxID + 118, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntitySumoruguru.class, "Sumoruguru", idxID + 119, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntitySupekutetto.class, "Supekutetto", idxID + 120, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntitySura2.class, "Sura2", idxID + 121, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntitySuraimubogu.class, "Suraimubogu", idxID + 122, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntitySuraimuburesu.class, "Suraimuburesu", idxID + 123, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntitySuraimuking.class, "Suraimuking", idxID + 124, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntitySyado.class, "Syado", idxID + 125, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityTahodoraki.class, "Tahodoraki", idxID + 126, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityTomosibikozou.class, "Tomosibikozou", idxID + 127, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityTonburero.class, "Tonburero", idxID + 128, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityTutiwarasi.class, "Tutiwarasi", idxID + 129, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityUmiusi.class, "Umiusi", idxID + 130, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityYouganmajin.class, "Youganmajin", idxID + 131, DQM.instance, 250, 1, false);


		EntityRegistry.registerModEntity(DqmEntityAnkokumajin.class, "Ankokumajin", idxID + 152, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityAroinpu.class, "Aroinpu", idxID + 153, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityBaburuking.class, "Baburuking", idxID + 154, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityBarakku.class, "Barakku", idxID + 155, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityBariidodog.class, "Bariidodog", idxID + 156, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityBatorurex.class, "Batorurex", idxID + 157, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityBehomasuraimu.class, "Behomasuraimu", idxID + 158, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityBiggufeisu.class, "Biggufeisu", idxID + 159, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityBoureikensi.class, "Boureikensi", idxID + 160, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityBuraddosodo.class, "Buraddosodo", idxID + 161, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityBurakkubejita.class, "Burakkubejita", idxID + 162, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityDarkslime.class, "Darkslime", idxID + 163, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityDeddopekka.class, "Deddopekka", idxID + 164, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityDgizumo.class, "Dgizumo", idxID + 165, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityDollmaster.class, "Dollmaster", idxID + 166, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityDqmdragon.class, "Dqmdragon", idxID + 167, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityDragonnaito.class, "Dragonnaito", idxID + 168, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityDragonraida.class, "Dragonraida", idxID + 169, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityGamegon.class, "Gamegon", idxID + 170, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityGamegonload.class, "Gamegonload", idxID + 171, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityGanirasu.class, "Ganirasu", idxID + 172, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityGoldman.class, "Goldman", idxID + 173, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityGoremu.class, "Goremu", idxID + 174, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityGorudensuraimu.class, "Gorudensuraimu", idxID + 175, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityHotatewarabi.class, "Hotatewarabi", idxID + 176, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityJigokunohasami.class, "Jigokunohasami", idxID + 177, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityKemunkurusu.class, "Kemunkurusu", idxID + 178, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityKirakurabu.class, "Kirakurabu", idxID + 179, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityKiramasin.class, "Kiramasin", idxID + 180, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityKisudragon.class, "Kisudragon", idxID + 181, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityKuinsuraimu.class, "Kuinsuraimu", idxID + 182, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityMagematango.class, "Magematango", idxID + 183, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityMagemomonja.class, "Magemomonja", idxID + 184, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityMagumaron.class, "Magumaron", idxID + 185, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityMajikaruhatto.class, "Majikaruhatto", idxID + 186, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityMaounokage.class, "Maounokage", idxID + 187, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityMaporena.class, "Maporena", idxID + 188, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityMegazarurokku.class, "Megazarurokku", idxID + 189, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityMetaruhanta.class, "Metaruhanta", idxID + 190, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityMetaruhantaken.class, "Metaruhantaken", idxID + 191, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityPandorabox.class, "Pandorabox", idxID + 192, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityPandorakibako.class, "Pandorakibako", idxID + 193, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityPikusi.class, "Pikusi", idxID + 194, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityPombom.class, "Pombom", idxID + 195, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityPuyon.class, "Puyon", idxID + 196, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityRedsaikuron.class, "Redsaikuron", idxID + 197, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntitySaikuropusu.class, "Saikuropusu", idxID + 198, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntitySirubadebiru.class, "Sirubadebiru", idxID + 199, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntitySiryounokisi.class, "Siryounokisi", idxID + 200, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntitySodofantomu.class, "Sodofantomu", idxID + 201, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityStarkimera.class, "Starkimera", idxID + 202, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityStonman.class, "Stonman", idxID + 203, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntitySuraimubehomazun.class, "Suraimubehomazun", idxID + 204, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntitySuraimuhaitawa.class, "Suraimuhaitawa", idxID + 205, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntitySuraimumadyura.class, "Suraimumadyura", idxID + 206, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityTubokku.class, "Tubokku", idxID + 207, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityUmibouzu.class, "Umibouzu", idxID + 208, DQM.instance, 250, 1, false);

		EntityRegistry.registerModEntity(DqmEntityAkairai.class, "Akairai", idxID + 250, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityBiggumoai.class, "Biggumoai", idxID + 253, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityDakuhobitto.class, "Dakuhobitto", idxID + 254, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityDakunaito.class, "Dakunaito", idxID + 255, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityDasudragon.class, "Dasudragon", idxID + 256, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityDebirurodo.class, "Debirurodo", idxID + 257, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityDenga.class, "Denga", idxID + 258, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityDesujakkaru.class, "Desujakkaru", idxID + 259, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityDragondarknaito.class, "Dragondarknaito", idxID + 260, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityGamegonrejendo.class, "Gamegonrejendo", idxID + 261, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityGigantesu.class, "Gigantesu", idxID + 262, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityGodraida.class, "Godraida", idxID + 263, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityKagenokisi.class, "Kagenokisi", idxID + 264, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityRyuiso.class, "Ryuiso", idxID + 265, DQM.instance, 250, 1, false);


		EntityRegistry.registerModEntity(DqmEntityArukemisuton.class, "Arukemisuton", idxID + 271, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityAtorasu.class, "Atorasu", idxID + 273, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityGodonheddo.class, "Godonheddo", idxID + 276, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityGorudenkon.class, "Gorudenkon", idxID + 277, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityKirapike.class, "Kirapike", idxID + 279, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityKiratoti.class, "Kiratoti", idxID + 280, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityKuinmomon.class, "Kuinmomon", idxID + 281, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityMaaburun.class, "Maaburun", idxID + 283, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityMashougumo.class, "Mashougumo", idxID + 284, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityMoonkimera.class, "Moonkimera", idxID + 286, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityReddoatya.class, "Reddoatya", idxID + 289, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntitySeigin.class, "Seigin", idxID + 291, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntitySirubamanto.class, "Sirubamanto", idxID + 292, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityTaipug.class, "Taipug", idxID + 294, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityTogekonbou.class, "Togekonbou", idxID + 295, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityTyokonuba.class, "Tyokonuba", idxID + 296, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityWanpakusatan.class, "Wanpakusatan", idxID + 297, DQM.instance, 250, 1, false);

		EntityRegistry.registerModEntity(DqmEntityDaiyamondosuraimu.class, "Daiyamondosuraimu", idxID + 304, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityDragometaru.class, "Dragometaru", idxID + 305, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityHagumeta.class, "Hagumeta", idxID + 306, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityHaguremetaruking.class, "Haguremetaruking", idxID + 307, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityMetaking.class, "Metaking", idxID + 308, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityMetaruburazazu.class, "Metaruburazazu", idxID + 309, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityMetasura.class, "Metasura", idxID + 310, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityPuratinaking.class, "Puratinaking", idxID + 311, DQM.instance, 250, 1, false);

		EntityRegistry.registerModEntity(DqmEntityBazuzu.class, "Bazuzu", idxID + 321, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityDarkRamia.class, "DarkRamia", idxID + 322, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityDesupisaro1.class, "Desupisaro1", idxID + 323, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityDesupisaro2.class, "Desupisaro2", idxID + 324, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityDesupisaro3.class, "Desupisaro3", idxID + 325, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityEsterk.class, "Esterk", idxID + 326, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityGod.class, "God", idxID + 327, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityKiramajinga.class, "Kiramajinga", idxID + 328, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityMasterdoragon.class, "Masterdoragon", idxID + 329, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityNorowaretaturugi.class, "Norowaretaturugi", idxID + 330, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityRyuuou.class, "Ryuuou", idxID + 331, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityRyuuou2.class, "Ryuuou2", idxID + 332, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntitySuraimujeneraru.class, "Suraimujeneraru", idxID + 333, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityYamatanooroti.class, "Yamatanooroti", idxID + 334, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityZoma.class, "Zoma", idxID + 335, DQM.instance, 250, 1, false);

		EntityRegistry.registerModEntity(DqmEntityAxedoragon.class, "Axedoragon", idxID + 500, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityBassaimasin.class, "Bassaimasin", idxID + 501, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityBesuking.class, "Besuking", idxID + 502, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityBighanma.class, "Bighanma", idxID + 503, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityBosutororu.class, "Bosutororu", idxID + 504, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityBurizado.class, "Burizado", idxID + 505, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityDansunidoru.class, "Dansunidoru", idxID + 506, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityDarktororu.class, "Darktororu", idxID + 507, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityDesunyago.class, "Desunyago", idxID + 508, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityDoragonsoruja.class, "Doragonsoruja", idxID + 509, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityDoroningyou.class, "Doroningyou", idxID + 510, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityDoruido.class, "Doruido", idxID + 511, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityEbiruapple.class, "Ebiruapple", idxID + 512, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityFaratto.class, "Faratto", idxID + 513, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityFureimu.class, "Fureimu", idxID + 514, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityGaikotu.class, "Gaikotu", idxID + 515, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityGappurin.class, "Gappurin", idxID + 516, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityGenjutusi.class, "Genjutusi", idxID + 517, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityGoldmanto.class, "Goldmanto", idxID + 518, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityHatonaito.class, "Hatonaito", idxID + 519, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityJigokunoyoroi.class, "Jigokunoyoroi", idxID + 520, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityKandatakobun.class, "Kandatakobun", idxID + 521, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityKedamon.class, "Kedamon", idxID + 522, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityKimendousi.class, "Kimendousi", idxID + 523, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityKiraama.class, "Kiraama", idxID + 524, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityKiramasin2.class, "Kiramasin2", idxID + 525, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityManemane.class, "Manemane", idxID + 526, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityMasso.class, "Masso", idxID + 527, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityMetaruhoimin.class, "Metaruhoimin", idxID + 528, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityMokomokojuu.class, "Mokomokojuu", idxID + 529, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityMomoirosansimai.class, "Momoirosansimai", idxID + 530, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityNoroinoiwa.class, "Noroinoiwa", idxID + 531, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityPapettoman.class, "Papettoman", idxID + 532, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityPinkbonbon.class, "Pinkbonbon", idxID + 533, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityPisaronaito.class, "Pisaronaito", idxID + 534, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityPuremiasuraimu.class, "Puremiasuraimu", idxID + 535, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityRaimusuraimu.class, "Raimusuraimu", idxID + 536, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityRemonsuraimu.class, "Remonsuraimu", idxID + 537, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntitySabotenboru.class, "Sabotenboru", idxID + 538, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntitySabotengold.class, "Sabotengold", idxID + 539, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntitySamayouyoroi.class, "Samayouyoroi", idxID + 540, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntitySirudoaniki.class, "Sirudoaniki", idxID + 541, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntitySiryou.class, "Siryou", idxID + 542, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityTattyan.class, "Tattyan", idxID + 543, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityTororu.class, "Tororu", idxID + 544, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityTororubakkosu.class, "Tororubakkosu", idxID + 545, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityTororubonba.class, "Tororubonba", idxID + 546, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityTororuking.class, "Tororuking", idxID + 547, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityTumurinmama.class, "Tumurinmama", idxID + 548, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityUragirikozou.class, "Uragirikozou", idxID + 549, DQM.instance, 250, 1, false);

		EntityRegistry.registerModEntity(DqmEntityMadrainbow.class, "Madrainbow", idxID + 550, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntitySweetbag.class, "Sweetbag", idxID + 551, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityShuvaluts.class, "Shuvaluts", idxID + 552, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityBebingosatan.class, "Bebingosatan", idxID + 553, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityKinghidora.class, "Kinghidora", idxID + 554, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityKingbesu.class, "Kingbesu", idxID + 555, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityBurasu.class, "Burasu", idxID + 556, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityGoldenmetalslime.class, "Goldenmetalslime", idxID + 557, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityFureizado.class, "Fureizado", idxID + 558, DQM.instance, 250, 1, false);

		EntityRegistry.registerModEntity(DqmEntityGorotuki.class, "Gorotuki", idxID + 559, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityEriminator.class, "Eriminator", idxID + 560, DQM.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityDesusutoka.class, "Desusutoka", idxID + 561, DQM.instance, 250, 1, false);
		//EntityRegistry.registerModEntity(DqmEntityKandata.class, "Gorotuki", idxID + 559, DQM.instance, 250, 1, false);

	}
}
