package dqmIII.blocks;

import net.minecraft.block.Block;
import net.minecraft.block.material.Material;
import dqmIII.DQM;
import dqmIII.blocks.decorate.DqmBlockAkumanotubo;
import dqmIII.blocks.decorate.DqmBlockAkumanotubo2;
import dqmIII.blocks.decorate.DqmBlockBed1;
import dqmIII.blocks.decorate.DqmBlockBed2;
import dqmIII.blocks.decorate.DqmBlockBlockSword;
import dqmIII.blocks.decorate.DqmBlockBlockSword2;
import dqmIII.blocks.decorate.DqmBlockBlockSword2Mob;
import dqmIII.blocks.decorate.DqmBlockBlockSwordMob;
import dqmIII.blocks.decorate.DqmBlockBlockTue;
import dqmIII.blocks.decorate.DqmBlockBouguya;
import dqmIII.blocks.decorate.DqmBlockBukiya;
import dqmIII.blocks.decorate.DqmBlockDaiza;
import dqmIII.blocks.decorate.DqmBlockDouguya;
import dqmIII.blocks.decorate.DqmBlockEntotu;
import dqmIII.blocks.decorate.DqmBlockHasira;
import dqmIII.blocks.decorate.DqmBlockHasiranaka;
import dqmIII.blocks.decorate.DqmBlockHasiraue;
import dqmIII.blocks.decorate.DqmBlockHepaitosu;
import dqmIII.blocks.decorate.DqmBlockHondana;
import dqmIII.blocks.decorate.DqmBlockIdo;
import dqmIII.blocks.decorate.DqmBlockIdooke;
import dqmIII.blocks.decorate.DqmBlockIsu;
import dqmIII.blocks.decorate.DqmBlockJuujika;
import dqmIII.blocks.decorate.DqmBlockKagaribidai;
import dqmIII.blocks.decorate.DqmBlockKen;
import dqmIII.blocks.decorate.DqmBlockKen2;
import dqmIII.blocks.decorate.DqmBlockKinoisi;
import dqmIII.blocks.decorate.DqmBlockMainSikabane;
import dqmIII.blocks.decorate.DqmBlockMainSikabaneMob;
import dqmIII.blocks.decorate.DqmBlockMaki;
import dqmIII.blocks.decorate.DqmBlockMinidama;
import dqmIII.blocks.decorate.DqmBlockOke;
import dqmIII.blocks.decorate.DqmBlockOokiihasiranaka;
import dqmIII.blocks.decorate.DqmBlockOokiihasirasita;
import dqmIII.blocks.decorate.DqmBlockOokiihasiraue;
import dqmIII.blocks.decorate.DqmBlockOokiiisizukue;
import dqmIII.blocks.decorate.DqmBlockOokiitukue;
import dqmIII.blocks.decorate.DqmBlockRotomon;
import dqmIII.blocks.decorate.DqmBlockRotonoturugiOb;
import dqmIII.blocks.decorate.DqmBlockSBatorurex;
import dqmIII.blocks.decorate.DqmBlockSBoureikensi;
import dqmIII.blocks.decorate.DqmBlockSGoremu;
import dqmIII.blocks.decorate.DqmBlockSKirapan;
import dqmIII.blocks.decorate.DqmBlockSSura;
import dqmIII.blocks.decorate.DqmBlockSSuraimunaito;
import dqmIII.blocks.decorate.DqmBlockSZukkinya;
import dqmIII.blocks.decorate.DqmBlockSikabaneK;
import dqmIII.blocks.decorate.DqmBlockTaimatu;
import dqmIII.blocks.decorate.DqmBlockTaimatu2;
import dqmIII.blocks.decorate.DqmBlockTaru;
import dqmIII.blocks.decorate.DqmBlockTaruK;
import dqmIII.blocks.decorate.DqmBlockTaruMob;
import dqmIII.blocks.decorate.DqmBlockTiisaitukue;
import dqmIII.blocks.decorate.DqmBlockTokusyutaimatu;
import dqmIII.blocks.decorate.DqmBlockTubo;
import dqmIII.blocks.decorate.DqmBlockTubo2;
import dqmIII.blocks.decorate.DqmBlockTuboK;
import dqmIII.blocks.decorate.DqmBlockTubokku;
import dqmIII.blocks.decorate.DqmBlockTubokku2;
import dqmIII.blocks.decorate.DqmBlockTueK;
import dqmIII.blocks.decorate.DqmBlockWakanai;
import dqmIII.blocks.decorate.DqmBlockYadoya;
import dqmIII.blocks.decorate.DqmBlockYajirusi;
import dqmIII.blocks.decorate.DqmBlockYajirusiMG;
import dqmIII.blocks.decorate.DqmBlockYajirusibatu;
import dqmIII.blocks.decorate.DqmBlockYajirusimaru;
import dqmIII.blocks.decorate.DqmBlockYajirusinaname;
import dqmIII.blocks.decorate.DqmBlockYajirusisita;
import dqmIII.blocks.decorate.DqmBlockYajirusiue;
import dqmIII.blocks.decorate.DqmFarmBookshelf;

public class DqmBlockDecorate {
	public static Block DqmBlockMinidama;





	public static Block DqmBlockTubo;
	public static Block DqmBlockTubokku;
	public static Block DqmBlockAkumanotubo;
	public static Block DqmBlockTubo2;
	public static Block DqmBlockTubokku2;
	public static Block DqmBlockAkumanotubo2;
	public static Block DqmBlockSword;
	public static Block DqmBlockSword2;
	public static Block DqmBlockDqmbed;
	public static Block DqmBlockDqmbed2;
	public static Block DqmBlockTue;
	public static Block DqmBlockSikabane;
	public static Block DqmBlockHikariB2;
	public static Block DqmBlockYajirusidaidai;
	public static Block DqmBlockYajirusihai;
	public static Block DqmBlockYajirusisiro;
	public static Block DqmBlockYajirusiaka;
	public static Block DqmBlockYajirusikuro;
	public static Block DqmBlockYajirusitya;
	public static Block DqmBlockYajirusikoimidori;
	public static Block DqmBlockYajirusimurasaki;
	public static Block DqmBlockYajirusiao;
	public static Block DqmBlockYajirusikiiro;
	public static Block DqmBlockYajirusimidori;
	public static Block DqmBlockYajirusipink;
	public static Block DqmBlockYajirusiusuao;
	public static Block DqmBlockYajirusikon;
	public static Block DqmBlockWakanai;
	public static Block DqmBlockYajirusidaidai2;
	public static Block DqmBlockYajirusihai2;
	public static Block DqmBlockYajirusisiro2;
	public static Block DqmBlockYajirusiaka2;
	public static Block DqmBlockYajirusikuro2;
	public static Block DqmBlockYajirusitya2;
	public static Block DqmBlockYajirusikoimidori2;
	public static Block DqmBlockYajirusimurasaki2;
	public static Block DqmBlockYajirusiao2;
	public static Block DqmBlockYajirusikiiro2;
	public static Block DqmBlockYajirusimidori2;
	public static Block DqmBlockYajirusipink2;
	public static Block DqmBlockYajirusiusuao2;
	public static Block DqmBlockYajirusikon2;
	public static Block DqmBlockYajirusiUe;
	public static Block DqmBlockYajirusiSita;
	public static Block DqmBlockYajirusiMaru;
	public static Block DqmBlockYajirusiBatu;
	public static Block DqmBlockDaizaQ;
	public static Block DqmBlockDaizaQG;
	public static Block DqmBlockDaizaB;
	public static Block DqmBlockDaizaBG;
	public static Block DqmBlockDaizaD;
	public static Block DqmBlockDaizaDG;
	public static Block DqmBlockDaizaE;
	public static Block DqmBlockDaizaEG;
	public static Block DqmBlockDaizaG;
	public static Block DqmBlockDaizaGG;
	public static Block DqmBlockDaizaI;
	public static Block DqmBlockDaizaIG;
	public static Block DqmBlockDaizaL;
	public static Block DqmBlockDaizaLG;
	public static Block DqmBlockDaizaN;
	public static Block DqmBlockDaizaNG;
	public static Block DqmBlockDaizaO;
	public static Block DqmBlockDaizaOG;
	public static Block DqmBlockDaizaR;
	public static Block DqmBlockDaizaRG;
	public static Block DqmBlockDaizaS;
	public static Block DqmBlockDaizaSG;
	public static Block DqmBlockDaizaW;
	public static Block DqmBlockDaizaWG;
	public static Block DqmBlockHepaitosu;
	public static Block DqmBlockRotomon;
	public static Block DqmBlockRotonoturugiOb;
	public static Block DqmBlockRotonoturugiOb2;
	public static Block DqmBlockRotonoturugiF;
	public static Block DqmBlockRotonoturugiF2;
	public static Block DqmBlockRotonoturugiMob;
	public static Block DqmBlockIsu;
	public static Block DqmBlockTaimatu;
	public static Block DqmBlockTaimatu2;
	public static Block DqmBlockTaru;

	public static Block DqmBlockHasiraNB;
	public static Block DqmBlockHasiranakaNB;
	public static Block DqmBlockHasiraueNB;

	public static Block DqmBlockHasira;
	public static Block DqmBlockHasiraQ;
	public static Block DqmBlockHasiranaka;
	public static Block DqmBlockHasiranakaQ;
	public static Block DqmBlockHasiraue;
	public static Block DqmBlockHasiraueQ;
	public static Block DqmBlockSwordMob;
	public static Block DqmBlockSword2Mob;
	public static Block DqmBlockKen2;
	public static Block DqmBlockKen;
	public static Block DqmBlockTueK;
	public static Block DqmBlockSikabaneK;
	public static Block DqmBlockTaruMob;
	public static Block DqmBlockSikabaneMob;
	public static Block DqmBlockJuujika;
	public static Block DqmBlockJuujika2;
	public static Block DqmBlockKagaribidai;
	public static Block DqmBlockOokiiisizukue;
	public static Block DqmBlockIdooke;
	public static Block DqmBlockOokiitukue;
	public static Block DqmBlockMaki;
	public static Block DqmBlockOke;
	public static Block DqmBlockIdo;
	public static Block DqmBlockKinoisi;
	public static Block DqmBlockTiisaitukue;
	public static Block DqmBlockHondana;
	public static Block DqmBlockOokiihasiraue;
	public static Block DqmBlockOokiihasirasita;
	public static Block DqmBlockOokiihasiranaka;
	public static Block DqmBlockOokiihasiraueQ;
	public static Block DqmBlockOokiihasirasitaQ;
	public static Block DqmBlockOokiihasiranakaQ;
	public static Block DqmBlockOokiihasiraueS;
	public static Block DqmBlockOokiihasirasitaS;
	public static Block DqmBlockOokiihasiranakaS;
	public static Block DqmBlockOokiihasiraueNB;
	public static Block DqmBlockOokiihasirasitaNB;
	public static Block DqmBlockOokiihasiranakaNB;
	public static Block DqmBlockTokusyutaimatu;
	public static Block DqmBlockEntotu;
	public static Block DqmBlockEntotuS;
	public static Block DqmBlockEntotuN;
	public static Block DqmBlockEntotuG;
	public static Block DqmBlockEntotuO;
	public static Block DqmBlockYadoya;
	public static Block DqmBlockDouguya;
	public static Block DqmBlockBouguya;
	public static Block DqmBlockBukiya;
	public static Block DqmBlockTaruK;
	public static Block DqmBlockTuboK;
	public static Block DqmBlockSBatorurex;
	public static Block DqmBlockSBoureikensi;
	public static Block DqmBlockSGoremu;
	public static Block DqmBlockSKirapan;
	public static Block DqmBlockSSura;
	public static Block DqmBlockSSuraimunaito;
	public static Block DqmBlockSZukkinya;
	public static Block DqmBlockFarmBookShelf;

	public DqmBlockDecorate()
	{
		DqmBlockMinidama = new DqmBlockMinidama(Material.rock).setHardness(0.6F).setStepSound(Block.soundTypeStone).setBlockName("dqm.blockMinidama").setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:miniDama");

		DqmBlockTubo = new DqmBlockTubo(Material.wood).setmodel("Tubo").setStepSound(Block.soundTypeGlass).setBlockName("dqm.blockTubo").setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:Tubo");
		DqmBlockTubokku = new DqmBlockTubokku(Material.rock).setmodel("Tubokku").setStepSound(Block.soundTypeGlass).setBlockName("dqm.blockTubokku").setHardness(5.0f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:Tubokku");
		DqmBlockAkumanotubo = new DqmBlockAkumanotubo(Material.iron).setmodel("Akumanotubo").setStepSound(Block.soundTypeGlass).setBlockName("dqm.blockAkumanotubo").setHardness(3.0f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:Akumanotubo");
		DqmBlockTubo2 = new DqmBlockTubo2(Material.wood).setmodel("Tubo2").setStepSound(Block.soundTypeGlass).setBlockName("dqm.blockTubo2").setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:Tubo");
		DqmBlockTubokku2 = new DqmBlockTubokku2(Material.rock).setmodel("Tubokku2").setStepSound(Block.soundTypeGlass).setBlockName("dqm.blockTubokku2").setHardness(5.0f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:Tubokku");
		DqmBlockAkumanotubo2 = new DqmBlockAkumanotubo2(Material.iron).setmodel("Akumanotubo2").setStepSound(Block.soundTypeGlass).setBlockName("dqm.blockAkumanotubo2").setHardness(3.0f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:Akumanotubo");
		DqmBlockSword = new DqmBlockBlockSword(Material.wood).setmodel("Sword").setStepSound(Block.soundTypeStone).setBlockName("dqm.blockSword").setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:SwordsB");
		DqmBlockSword2 = new DqmBlockBlockSword2(Material.wood).setmodel("Sword2").setStepSound(Block.soundTypeStone).setBlockName("dqm.blockSword2").setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:SwordB");
		DqmBlockDqmbed = new DqmBlockBed1(Material.wood).setStepSound(Block.soundTypeCloth).setBlockName("dqm.blockDqmbed").setHardness(20.0f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:DqmbedB");
		DqmBlockDqmbed2 = new DqmBlockBed2(Material.wood).setStepSound(Block.soundTypeCloth).setBlockName("dqm.blockDqmbed2").setHardness(20.0f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:Dqmbed2B");
		DqmBlockTue = new DqmBlockBlockTue(Material.wood).setStepSound(Block.soundTypeStone).setBlockName("dqm.blockTue").setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:TueB");
		DqmBlockSikabane = new DqmBlockMainSikabane(Material.wood).setStepSound(Block.soundTypeStone).setBlockName("dqm.blockSikabane").setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:Sikabane");
		//***********************************************************************スライム矢印******************************************************************************************
		DqmBlockHikariB2 = new DqmBlockYajirusiMG(Material.wood).setmodel("HikariB2").setStepSound(Block.soundTypeGlass).setLightLevel(1.0F).setBlockName("dqm.blockHikariB2").setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:HikariB2");
		DqmBlockYajirusidaidai = new DqmBlockYajirusi(Material.wood).setmodel("Yajirusidaidai").setStepSound(Block.soundTypeGlass).setLightLevel(1.0F).setBlockName("dqm.blockYajirusidaidai").setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:YajirusiB");
		DqmBlockYajirusihai = new DqmBlockYajirusi(Material.wood).setmodel("Yajirusihai").setStepSound(Block.soundTypeGlass).setLightLevel(1.0F).setBlockName("dqm.blockYajirusihai").setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:YajirusiB");
		DqmBlockYajirusisiro = new DqmBlockYajirusi(Material.wood).setmodel("Yajirusisiro").setStepSound(Block.soundTypeGlass).setLightLevel(1.0F).setBlockName("dqm.blockYajirusisiro").setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:YajirusiB");
		DqmBlockYajirusiaka = new DqmBlockYajirusi(Material.wood).setmodel("Yajirusiaka").setStepSound(Block.soundTypeGlass).setLightLevel(1.0F).setBlockName("dqm.blockYajirusiaka").setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:YajirusiB");
		DqmBlockYajirusikuro = new DqmBlockYajirusi(Material.wood).setmodel("Yajirusikuro").setStepSound(Block.soundTypeGlass).setLightLevel(1.0F).setBlockName("dqm.blockYajirusikuro").setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:YajirusiB");
		DqmBlockYajirusitya = new DqmBlockYajirusi(Material.wood).setmodel("Yajirusitya").setStepSound(Block.soundTypeGlass).setLightLevel(1.0F).setBlockName("dqm.blockYajirusitya").setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:YajirusiB");
		DqmBlockYajirusikoimidori = new DqmBlockYajirusi(Material.wood).setmodel("Yajirusikoimidori").setStepSound(Block.soundTypeGlass).setLightLevel(1.0F).setBlockName("dqm.blockYajirusikoimidori").setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:YajirusiB");
		DqmBlockYajirusimurasaki = new DqmBlockYajirusi(Material.wood).setmodel("Yajirusimurasaki").setStepSound(Block.soundTypeGlass).setLightLevel(1.0F).setBlockName("dqm.blockYajirusimurasaki").setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:YajirusiB");
		DqmBlockYajirusiao = new DqmBlockYajirusi(Material.wood).setmodel("Yajirusiao").setStepSound(Block.soundTypeGlass).setLightLevel(1.0F).setBlockName("dqm.blockYajirusiao").setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:YajirusiB");
		DqmBlockYajirusikiiro = new DqmBlockYajirusi(Material.wood).setmodel("Yajirusikiiro").setStepSound(Block.soundTypeGlass).setLightLevel(1.0F).setBlockName("dqm.blockYajirusikiiro").setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:YajirusiB");
		DqmBlockYajirusimidori = new DqmBlockYajirusi(Material.wood).setmodel("Yajirusimidori").setStepSound(Block.soundTypeGlass).setLightLevel(1.0F).setBlockName("dqm.blockYajirusimidori").setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:YajirusiB");
		DqmBlockYajirusipink = new DqmBlockYajirusi(Material.wood).setmodel("Yajirusipink").setStepSound(Block.soundTypeGlass).setLightLevel(1.0F).setBlockName("dqm.blockYajirusipink").setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:YajirusiB");
		DqmBlockYajirusiusuao = new DqmBlockYajirusi(Material.wood).setmodel("Yajirusiusuao").setStepSound(Block.soundTypeGlass).setLightLevel(1.0F).setBlockName("dqm.blockYajirusiusuao").setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:YajirusiB");
		DqmBlockYajirusikon = new DqmBlockYajirusi(Material.wood).setmodel("Yajirusikon").setStepSound(Block.soundTypeGlass).setLightLevel(1.0F).setBlockName("dqm.blockYajirusikon").setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:YajirusiB");
		DqmBlockWakanai = new DqmBlockWakanai(Material.wood).setBlockName("dqm.blockWakanai").setStepSound(Block.soundTypeGlass).setResistance(2000.0F).setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:Wakanai");
		//斜め
		DqmBlockYajirusidaidai2 = new DqmBlockYajirusinaname(Material.wood).setmodel("Yajirusidaidai2").setStepSound(Block.soundTypeGlass).setLightLevel(1.0F).setBlockName("dqm.blockYajirusidaidai2").setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:YajirusinanameB");
		DqmBlockYajirusihai2 = new DqmBlockYajirusinaname(Material.wood).setmodel("Yajirusihai2").setStepSound(Block.soundTypeGlass).setLightLevel(1.0F).setBlockName("dqm.blockYajirusihai2").setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:YajirusinanameB");
		DqmBlockYajirusisiro2 = new DqmBlockYajirusinaname(Material.wood).setmodel("Yajirusisiro2").setStepSound(Block.soundTypeGlass).setLightLevel(1.0F).setBlockName("dqm.blockYajirusisiro2").setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:YajirusinanameB");
		DqmBlockYajirusiaka2 = new DqmBlockYajirusinaname(Material.wood).setmodel("Yajirusiaka2").setStepSound(Block.soundTypeGlass).setLightLevel(1.0F).setBlockName("dqm.blockYajirusiaka2").setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:YajirusinanameB");
		DqmBlockYajirusikuro2 = new DqmBlockYajirusinaname(Material.wood).setmodel("Yajirusikuro2").setStepSound(Block.soundTypeGlass).setLightLevel(1.0F).setBlockName("dqm.blockYajirusikuro2").setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:YajirusinanameB");
		DqmBlockYajirusitya2 = new DqmBlockYajirusinaname(Material.wood).setmodel("Yajirusitya2").setStepSound(Block.soundTypeGlass).setLightLevel(1.0F).setBlockName("dqm.blockYajirusitya2").setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:YajirusinanameB");
		DqmBlockYajirusikoimidori2 = new DqmBlockYajirusinaname(Material.wood).setmodel("Yajirusikoimidori2").setStepSound(Block.soundTypeGlass).setLightLevel(1.0F).setBlockName("dqm.blockYajirusikoimidori2").setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:YajirusinanameB");
		DqmBlockYajirusimurasaki2 = new DqmBlockYajirusinaname(Material.wood).setmodel("Yajirusimurasaki2").setStepSound(Block.soundTypeGlass).setLightLevel(1.0F).setBlockName("dqm.blockYajirusimurasaki2").setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:YajirusinanameB");
		DqmBlockYajirusiao2 = new DqmBlockYajirusinaname(Material.wood).setmodel("Yajirusiao2").setStepSound(Block.soundTypeGlass).setLightLevel(1.0F).setBlockName("dqm.blockYajirusiao2").setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:YajirusinanameB");
		DqmBlockYajirusikiiro2 = new DqmBlockYajirusinaname(Material.wood).setmodel("Yajirusikiiro2").setStepSound(Block.soundTypeGlass).setLightLevel(1.0F).setBlockName("dqm.blockYajirusikiiro2").setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:YajirusinanameB");
		DqmBlockYajirusimidori2 = new DqmBlockYajirusinaname(Material.wood).setmodel("Yajirusimidori2").setStepSound(Block.soundTypeGlass).setLightLevel(1.0F).setBlockName("dqm.blockYajirusimidori2").setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:YajirusinanameB");
		DqmBlockYajirusipink2 = new DqmBlockYajirusinaname(Material.wood).setmodel("Yajirusipink2").setStepSound(Block.soundTypeGlass).setLightLevel(1.0F).setBlockName("dqm.blockYajirusipink2").setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:YajirusinanameB");
		DqmBlockYajirusiusuao2 = new DqmBlockYajirusinaname(Material.wood).setmodel("Yajirusiusuao2").setStepSound(Block.soundTypeGlass).setLightLevel(1.0F).setBlockName("dqm.blockYajirusiusuao2").setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:YajirusinanameB");
		DqmBlockYajirusikon2 = new DqmBlockYajirusinaname(Material.wood).setmodel("Yajirusikon2").setStepSound(Block.soundTypeGlass).setLightLevel(1.0F).setBlockName("dqm.blockYajirusikon2").setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:YajirusinanameB");
		//上下
		DqmBlockYajirusiUe = new DqmBlockYajirusiue(Material.wood).setmodel("YajirusiUe").setStepSound(Block.soundTypeGlass).setLightLevel(1.0F).setBlockName("dqm.blockYajirusiUe").setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:YajirusiueB");
		DqmBlockYajirusiSita = new DqmBlockYajirusisita(Material.wood).setmodel("YajirusiSita").setStepSound(Block.soundTypeGlass).setLightLevel(1.0F).setBlockName("dqm.blockYajirusiSita").setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:YajirusisitaB");
		DqmBlockYajirusiMaru = new DqmBlockYajirusimaru(Material.wood).setmodel("YajirusiMaru").setStepSound(Block.soundTypeGlass).setLightLevel(1.0F).setBlockName("dqm.blockYajirusiMaru").setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:YajirusimaruB");
		DqmBlockYajirusiBatu = new DqmBlockYajirusibatu(Material.wood).setmodel("YajirusiBatu").setStepSound(Block.soundTypeGlass).setLightLevel(1.0F).setBlockName("dqm.blockYajirusiBatu").setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:YajirusibatuB");
		//台座
		DqmBlockDaizaQ = new DqmBlockDaiza(Material.wood).setmodel("DaizaQ").setBlockName("dqm.blockDaizaQ").setStepSound(Block.soundTypeStone).setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:DaizaB");
		DqmBlockDaizaQG = new DqmBlockDaiza(Material.wood).setmodel("DaizaQG").setBlockName("dqm.blockDaizaQG").setStepSound(Block.soundTypeStone).setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:DaizaB");
		DqmBlockDaizaB = new DqmBlockDaiza(Material.wood).setmodel("DaizaB").setBlockName("dqm.blockDaizaB").setStepSound(Block.soundTypeStone).setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:DaizaB");
		DqmBlockDaizaBG = new DqmBlockDaiza(Material.wood).setmodel("DaizaBG").setBlockName("dqm.blockDaizaBG").setStepSound(Block.soundTypeStone).setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:DaizaB");
		DqmBlockDaizaD = new DqmBlockDaiza(Material.wood).setmodel("DaizaD").setBlockName("dqm.blockDaizaD").setStepSound(Block.soundTypeStone).setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:DaizaB");
		DqmBlockDaizaDG = new DqmBlockDaiza(Material.wood).setmodel("DaizaDG").setBlockName("dqm.blockDaizaDG").setStepSound(Block.soundTypeStone).setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:DaizaB");
		DqmBlockDaizaE = new DqmBlockDaiza(Material.wood).setmodel("DaizaE").setBlockName("dqm.blockDaizaE").setStepSound(Block.soundTypeStone).setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:DaizaB");
		DqmBlockDaizaEG = new DqmBlockDaiza(Material.wood).setmodel("DaizaEG").setBlockName("dqm.blockDaizaEG").setStepSound(Block.soundTypeStone).setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:DaizaB");
		DqmBlockDaizaG = new DqmBlockDaiza(Material.wood).setmodel("DaizaG").setBlockName("dqm.blockDaizaG").setStepSound(Block.soundTypeStone).setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:DaizaB");
		DqmBlockDaizaGG = new DqmBlockDaiza(Material.wood).setmodel("DaizaGG").setBlockName("dqm.blockDaizaGG").setStepSound(Block.soundTypeStone).setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:DaizaB");
		DqmBlockDaizaI = new DqmBlockDaiza(Material.wood).setmodel("DaizaI").setBlockName("dqm.blockDaizaI").setStepSound(Block.soundTypeStone).setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:DaizaB");
		DqmBlockDaizaIG = new DqmBlockDaiza(Material.wood).setmodel("DaizaIG").setBlockName("dqm.blockDaizaIG").setStepSound(Block.soundTypeStone).setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:DaizaB");
		DqmBlockDaizaL = new DqmBlockDaiza(Material.wood).setmodel("DaizaL").setBlockName("dqm.blockDaizaL").setStepSound(Block.soundTypeStone).setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:DaizaB");
		DqmBlockDaizaLG = new DqmBlockDaiza(Material.wood).setmodel("DaizaLG").setBlockName("dqm.blockDaizaLG").setStepSound(Block.soundTypeStone).setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:DaizaB");
		DqmBlockDaizaN = new DqmBlockDaiza(Material.wood).setmodel("DaizaN").setBlockName("dqm.blockDaizaN").setStepSound(Block.soundTypeStone).setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:DaizaB");
		DqmBlockDaizaNG = new DqmBlockDaiza(Material.wood).setmodel("DaizaNG").setBlockName("dqm.blockDaizaNG").setStepSound(Block.soundTypeStone).setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:DaizaB");
		DqmBlockDaizaO = new DqmBlockDaiza(Material.wood).setmodel("DaizaO").setBlockName("dqm.blockDaizaO").setStepSound(Block.soundTypeStone).setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:DaizaB");
		DqmBlockDaizaOG = new DqmBlockDaiza(Material.wood).setmodel("DaizaOG").setBlockName("dqm.blockDaizaOG").setStepSound(Block.soundTypeStone).setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:DaizaB");
		DqmBlockDaizaR = new DqmBlockDaiza(Material.wood).setmodel("DaizaR").setBlockName("dqm.blockDaizaR").setStepSound(Block.soundTypeStone).setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:DaizaB");
		DqmBlockDaizaRG = new DqmBlockDaiza(Material.wood).setmodel("DaizaRG").setBlockName("dqm.blockDaizaRG").setStepSound(Block.soundTypeStone).setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:DaizaB");
		DqmBlockDaizaS = new DqmBlockDaiza(Material.wood).setmodel("DaizaS").setBlockName("dqm.blockDaizaS").setStepSound(Block.soundTypeStone).setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:DaizaB");
		DqmBlockDaizaSG = new DqmBlockDaiza(Material.wood).setmodel("DaizaSG").setBlockName("dqm.blockDaizaSG").setStepSound(Block.soundTypeStone).setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:DaizaB");
		DqmBlockDaizaW = new DqmBlockDaiza(Material.wood).setmodel("DaizaW").setBlockName("dqm.blockDaizaW").setStepSound(Block.soundTypeStone).setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:DaizaB");
		DqmBlockDaizaWG = new DqmBlockDaiza(Material.wood).setmodel("DaizaWG").setBlockName("dqm.blockDaizaWG").setStepSound(Block.soundTypeStone).setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:DaizaB");
		//その他
		DqmBlockHepaitosu = new DqmBlockHepaitosu(Material.wood).setmodel("Hepaitosu").setStepSound(Block.soundTypeGlass).setLightLevel(1.0F).setBlockName("dqm.blockHepaitosu").setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:Hepaitosunohidane");
		DqmBlockRotomon = new DqmBlockRotomon(Material.wood).setmodel("Rotomon").setStepSound(Block.soundTypeGlass).setBlockName("dqm.blockRotomon").setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:Rotonomonsyou");
		DqmBlockRotonoturugiOb = new DqmBlockRotonoturugiOb(Material.wood).setmodel("RotonoturugiOb").setStepSound(Block.soundTypeGlass).setBlockName("dqm.blockRotonoturugiOb").setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:RotonoturugiB");
		DqmBlockRotonoturugiOb2 = new DqmBlockRotonoturugiOb(Material.wood).setmodel("RotonoturugiOb2").setStepSound(Block.soundTypeGlass).setBlockName("dqm.blockRotonoturugiOb2").setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:RotonoturugiB");
		DqmBlockRotonoturugiF = new DqmBlockRotonoturugiOb(Material.wood).setmodel("RotonoturugiF").setStepSound(Block.soundTypeGlass).setBlockName("dqm.blockRotonoturugiF").setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:RotonoturugiB");
		DqmBlockRotonoturugiF2 = new DqmBlockRotonoturugiOb(Material.wood).setmodel("RotonoturugiF2").setStepSound(Block.soundTypeGlass).setBlockName("dqm.blockRotonoturugiF2").setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:RotonoturugiB");
		//RotonoturugiMob = new DqmBlockRotonoturugiMob(Material.wood,true).setmodel("RotonoturugiMob").setBlockName("dqm.blockRotonoturugiMob").setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:noturugiMob");
		DqmBlockIsu = new DqmBlockIsu(Material.wood).setmodel("Isu").setBlockName("dqm.blockIsu").setStepSound(Block.soundTypeWood).setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:IsuB");
		DqmBlockTaimatu = new DqmBlockTaimatu(Material.wood).setmodel("Taimatu").setLightLevel(1.0F).setStepSound(Block.soundTypeWood).setBlockName("dqm.blockTaimatu").setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:TaimatuB");
		DqmBlockTaimatu2 = new DqmBlockTaimatu2(Material.wood).setmodel("Taimatu2").setLightLevel(1.0F).setStepSound(Block.soundTypeWood).setBlockName("dqm.blockTaimatu2").setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:Taimatu2B");
		DqmBlockTaru = new DqmBlockTaru(Material.wood).setmodel("Taru").setBlockName("dqm.blockTaru").setStepSound(Block.soundTypeWood).setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:TaruB");
		DqmBlockHasira = new DqmBlockHasira(Material.wood).setmodel("Hasira").setBlockName("dqm.blockHasira").setStepSound(Block.soundTypeStone).setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:HasiraB");

		DqmBlockHasiraNB = new DqmBlockHasira(Material.wood).setmodel("HasiraNB").setBlockName("dqm.blockHasiraNB").setStepSound(Block.soundTypeStone).setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:HasiraB");
		DqmBlockHasiranakaNB = new DqmBlockHasiranaka(Material.wood).setmodel("HasiranakaNB").setBlockName("dqm.blockHasiranakaNB").setStepSound(Block.soundTypeStone).setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:HasiranakaB");
		DqmBlockHasiraueNB = new DqmBlockHasiraue(Material.wood).setmodel("HasiraueNB").setBlockName("dqm.blockHasiraueNB").setStepSound(Block.soundTypeStone).setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:HasiraueB");

		DqmBlockHasiraQ = new DqmBlockHasira(Material.wood).setmodel("HasiraQ").setBlockName("dqm.blockHasiraQ").setStepSound(Block.soundTypeStone).setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:HasiraB");
		DqmBlockHasiranaka = new DqmBlockHasiranaka(Material.wood).setmodel("Hasiranaka").setBlockName("dqm.blockHasiranaka").setStepSound(Block.soundTypeStone).setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:HasiranakaB");
		DqmBlockHasiranakaQ = new DqmBlockHasiranaka(Material.wood).setmodel("HasiranakaQ").setBlockName("dqm.blockHasiranakaQ").setStepSound(Block.soundTypeStone).setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:HasiranakaB");
		DqmBlockHasiraue = new DqmBlockHasiraue(Material.wood).setmodel("Hasiraue").setBlockName("dqm.blockHasiraue").setStepSound(Block.soundTypeStone).setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:HasiraueB");
		DqmBlockHasiraueQ = new DqmBlockHasiraue(Material.wood).setmodel("HasiraueQ").setBlockName("dqm.blockHasiraueQ").setStepSound(Block.soundTypeStone).setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:HasiraueB");
		DqmBlockSwordMob = new DqmBlockBlockSwordMob(Material.wood).setmodel("SwordMob").setBlockName("dqm.blockSwordMob").setStepSound(Block.soundTypeStone).setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:SwordsB");
		DqmBlockSword2Mob = new DqmBlockBlockSword2Mob(Material.wood).setmodel("Sword2Mob").setBlockName("dqm.blockSword2Mob").setStepSound(Block.soundTypeStone).setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:SwordB");
		DqmBlockKen2 = new DqmBlockKen2(Material.wood).setmodel("Ken2").setBlockName("dqm.blockKen2").setHardness(0.5f).setStepSound(Block.soundTypeStone).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:SwordB");
		DqmBlockKen = new DqmBlockKen(Material.wood).setmodel("Ken").setBlockName("dqm.blockKen").setHardness(0.5f).setStepSound(Block.soundTypeStone).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:SwordsB");
		DqmBlockTueK = new DqmBlockTueK(Material.wood).setmodel("TueK").setBlockName("dqm.blockTueK").setStepSound(Block.soundTypeWood).setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:TueB");
		DqmBlockSikabaneK = new DqmBlockSikabaneK(Material.wood).setmodel("SikabaneK").setBlockName("dqm.blockSikabaneK").setStepSound(Block.soundTypeStone).setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:Sikabane");
		DqmBlockTaruMob = new DqmBlockTaruMob(Material.wood).setmodel("TaruMob").setBlockName("dqm.blockTaruMob").setStepSound(Block.soundTypeWood).setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:TaruB");
		DqmBlockSikabaneMob = new DqmBlockMainSikabaneMob(Material.wood).setmodel("SikabaneMob").setBlockName("dqm.blockSikabaneMob").setStepSound(Block.soundTypeStone).setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:Sikabane");
		DqmBlockJuujika = new DqmBlockJuujika(Material.wood).setmodel("Juujika").setBlockName("dqm.blockJuujika").setStepSound(Block.soundTypeStone).setLightLevel(1.0F).setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:JuujikaB");
		DqmBlockJuujika2 = new DqmBlockJuujika(Material.wood).setmodel("Juujika2").setBlockName("dqm.blockJuujika2").setStepSound(Block.soundTypeStone).setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:JuujikaB");
		//New建材
		DqmBlockKagaribidai = new DqmBlockKagaribidai(Material.wood).setmodel("Kagaribidai").setBlockName("dqm.blockKagaribidai").setStepSound(Block.soundTypeStone).setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:KagaribiB");
		DqmBlockOokiiisizukue = new DqmBlockOokiiisizukue(Material.wood).setmodel("Ookiiisizukue").setBlockName("dqm.blockOokiiisizukue").setStepSound(Block.soundTypeStone).setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:IsinotukueB");
		DqmBlockIdooke = new DqmBlockIdooke(Material.wood).setmodel("Idooke").setBlockName("dqm.blockIdooke").setStepSound(Block.soundTypeWood).setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:IdookeB");
		DqmBlockOokiitukue = new DqmBlockOokiitukue(Material.wood).setmodel("Ookiitukue").setBlockName("dqm.blockOokiitukue").setStepSound(Block.soundTypeWood).setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:OokiikinotukueB");
		DqmBlockMaki = new DqmBlockMaki(Material.wood).setmodel("Maki").setBlockName("dqm.blockMaki").setStepSound(Block.soundTypeWood).setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:MakiB");
		DqmBlockOke = new DqmBlockOke(Material.wood).setmodel("Oke").setBlockName("dqm.blockOke").setStepSound(Block.soundTypeWood).setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:OkeB");
		DqmBlockIdo = new DqmBlockIdo(Material.wood).setmodel("Ido").setBlockName("dqm.blockIdo").setHardness(0.5f).setStepSound(Block.soundTypeStone).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:IdoB");
		DqmBlockKinoisi = new DqmBlockKinoisi(Material.wood).setmodel("Kinoisi").setBlockName("dqm.blockKinoisi").setStepSound(Block.soundTypeWood).setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:KinoisuB");
		DqmBlockTiisaitukue = new DqmBlockTiisaitukue(Material.wood).setmodel("Tiisaitukue").setBlockName("dqm.blockTiisaitukue").setStepSound(Block.soundTypeWood).setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:TiisaikinotukueB");
		DqmBlockHondana = new DqmBlockHondana(Material.wood).setmodel("Hondana").setBlockName("dqm.blockHondana").setStepSound(Block.soundTypeWood).setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:HondanaB");
		DqmBlockOokiihasiraue = new DqmBlockOokiihasiraue(Material.wood).setmodel("Ookiihasiraue").setBlockName("dqm.blockOokiihasiraue").setStepSound(Block.soundTypeStone).setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:OokiihaueB");
		DqmBlockOokiihasirasita = new DqmBlockOokiihasirasita(Material.wood).setmodel("Ookiihasirasita").setBlockName("dqm.blockOokiihasirasita").setStepSound(Block.soundTypeStone).setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:OokiihasitaB");
		DqmBlockOokiihasiranaka = new DqmBlockOokiihasiranaka(Material.wood).setmodel("Ookiihasiranaka").setBlockName("dqm.blockOokiihasiranaka").setStepSound(Block.soundTypeStone).setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:OokiihanakaB");
		DqmBlockOokiihasiraueQ = new DqmBlockOokiihasiraue(Material.wood).setmodel("OokiihasiraueQ").setBlockName("dqm.blockOokiihasiraueQ").setStepSound(Block.soundTypeStone).setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:OokiihaueB");
		DqmBlockOokiihasirasitaQ = new DqmBlockOokiihasirasita(Material.wood).setmodel("OokiihasirasitaQ").setBlockName("dqm.blockOokiihasirasitaQ").setStepSound(Block.soundTypeStone).setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:OokiihasitaB");
		DqmBlockOokiihasiranakaQ = new DqmBlockOokiihasiranaka(Material.wood).setmodel("OokiihasiranakaQ").setBlockName("dqm.blockOokiihasiranakaQ").setStepSound(Block.soundTypeStone).setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:OokiihanakaB");
		DqmBlockOokiihasiraueS = new DqmBlockOokiihasiraue(Material.wood).setmodel("OokiihasiraueS").setBlockName("dqm.blockOokiihasiraueS").setStepSound(Block.soundTypeStone).setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:OokiihaueB");
		DqmBlockOokiihasirasitaS = new DqmBlockOokiihasirasita(Material.wood).setmodel("OokiihasirasitaS").setBlockName("dqm.blockOokiihasirasitaS").setStepSound(Block.soundTypeStone).setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:OokiihasitaB");
		DqmBlockOokiihasiranakaS = new DqmBlockOokiihasiranaka(Material.wood).setmodel("OokiihasiranakaS").setBlockName("dqm.blockOokiihasiranakaS").setStepSound(Block.soundTypeStone).setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:OokiihanakaB");
		DqmBlockOokiihasiraueNB = new DqmBlockOokiihasiraue(Material.wood).setmodel("OokiihasiraueNB").setBlockName("dqm.blockOokiihasiraueNB").setStepSound(Block.soundTypeStone).setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:OokiihaueB");
		DqmBlockOokiihasirasitaNB = new DqmBlockOokiihasirasita(Material.wood).setmodel("OokiihasirasitaNB").setBlockName("dqm.blockOokiihasirasitaNB").setStepSound(Block.soundTypeStone).setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:OokiihasitaB");
		DqmBlockOokiihasiranakaNB = new DqmBlockOokiihasiranaka(Material.wood).setmodel("OokiihasiranakaNB").setBlockName("dqm.blockOokiihasiranakaNB").setStepSound(Block.soundTypeStone).setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:OokiihanakaB");
		DqmBlockTokusyutaimatu = new DqmBlockTokusyutaimatu(Material.wood).setmodel("Tokusyutaimatu").setLightLevel(1.0F).setStepSound(Block.soundTypeGlass).setBlockName("dqm.blockTokusyutaimatu").setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:TokusyutaimatuB");
		DqmBlockEntotu = new DqmBlockEntotu(Material.wood).setmodel("Entotu").setBlockName("dqm.blockEntotu").setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:EntotuB");
		DqmBlockEntotuS = new DqmBlockEntotu(Material.wood).setmodel("EntotuS").setBlockName("dqm.blockEntotuS").setStepSound(Block.soundTypeStone).setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:EntotuB");
		DqmBlockEntotuN = new DqmBlockEntotu(Material.wood).setmodel("EntotuN").setBlockName("dqm.blockEntotuN").setStepSound(Block.soundTypeStone).setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:EntotuB");
		DqmBlockEntotuG = new DqmBlockEntotu(Material.wood).setmodel("EntotuG").setBlockName("dqm.blockEntotuG").setStepSound(Block.soundTypeStone).setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:EntotuB");
		DqmBlockEntotuO = new DqmBlockEntotu(Material.wood).setmodel("EntotuO").setBlockName("dqm.blockEntotuO").setStepSound(Block.soundTypeStone).setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:EntotuB");
		DqmBlockYadoya = new DqmBlockYadoya(Material.wood).setmodel("Yadoya").setBlockName("dqm.blockYadoya").setStepSound(Block.soundTypeWood).setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:YadoyaB");
		DqmBlockDouguya = new DqmBlockDouguya(Material.wood).setmodel("Douguya").setBlockName("dqm.blockDouguya").setStepSound(Block.soundTypeWood).setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:DouguyaB");
		DqmBlockBouguya = new DqmBlockBouguya(Material.wood).setmodel("Bouguya").setBlockName("dqm.blockBouguya").setStepSound(Block.soundTypeWood).setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:BouguyaB");
		DqmBlockBukiya = new DqmBlockBukiya(Material.wood).setmodel("Bukiya").setBlockName("dqm.blockBukiya").setStepSound(Block.soundTypeWood).setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:BukiyaB");
		DqmBlockTaruK = new DqmBlockTaruK(Material.wood).setmodel("TaruK").setBlockName("dqm.blockTaruK").setStepSound(Block.soundTypeWood).setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:TaruB");
		DqmBlockTuboK = new DqmBlockTuboK(Material.wood).setmodel("TuboK").setBlockName("dqm.blockTuboK").setStepSound(Block.soundTypeGlass).setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:Tubo");
		DqmBlockSBatorurex = new DqmBlockSBatorurex(Material.wood).setmodel("SBatorurex").setBlockName("dqm.blockSBatorurex").setStepSound(Block.soundTypeStone).setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:SBatorurexB");
		DqmBlockSBoureikensi = new DqmBlockSBoureikensi(Material.wood).setmodel("SBoureikensi").setBlockName("dqm.blockSBoureikensi").setStepSound(Block.soundTypeStone).setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:SBoureikensiB");
		DqmBlockSGoremu = new DqmBlockSGoremu(Material.wood).setmodel("SGoremu").setBlockName("dqm.blockSGoremu").setStepSound(Block.soundTypeStone).setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:SGodraidaB");
		DqmBlockSKirapan = new DqmBlockSKirapan(Material.wood).setmodel("SKirapan").setBlockName("dqm.blockSKirapan").setStepSound(Block.soundTypeStone).setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:SKirapanB");
		DqmBlockSSura = new DqmBlockSSura(Material.wood).setmodel("SSura").setBlockName("dqm.blockSSura").setStepSound(Block.soundTypeStone).setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:SSuraB");
		DqmBlockSSuraimunaito = new DqmBlockSSuraimunaito(Material.wood).setmodel("SSuraimunaito").setStepSound(Block.soundTypeStone).setBlockName("dqm.blockSSuraimunaito").setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:SSuraimunaitoB");
		DqmBlockSZukkinya = new DqmBlockSZukkinya(Material.wood).setmodel("SZukkinya").setBlockName("dqm.blockSZukkinya").setStepSound(Block.soundTypeStone).setHardness(0.5f).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("dqm:SZukkinyaB");
		DqmBlockFarmBookShelf = new DqmFarmBookshelf().setBlockName("dqm.blockFarmBookShelf").setStepSound(Block.soundTypeWood).setCreativeTab(DQM.tabs.DqmTabDecorate).setBlockTextureName("bookshelf");



	}
}
